### ISSUE TITLE
Error When Running open_images_downloader.py

### ISSUE THREAD

**Issue by DJT777** [dusty-nv/jetson-inference#1024]
Hey dusty, I am trying to work through the transfer learning portion of your tutorial. I am getting some errors when attempting to use the open_images_downloader.py. I am wondering if you could have a look and help figure out why I am getting these errors.

```
user@tx1:/media/user/SD/jetson-inference/python/training/detection/ssd$  python3 open_images_downloader.py --class-names "Apple,Orange,Banana,Strawberry,Grape,Pear,Pineapple,Watermelon" --data=data/fruit
2021-04-25 16:46:07 - Download https://storage.googleapis.com/openimages/2018_04/class-descriptions-boxable.csv.
2021-04-25 16:46:07 - Requested 8 classes, found 8 classes
2021-04-25 16:46:07 - Download https://storage.googleapis.com/openimages/2018_04/train/train-annotations-bbox.csv.
2021-04-25 16:49:57 - Read annotation file data/fruit/train-annotations-bbox.csv
Traceback (most recent call last):
  File "open_images_downloader.py", line 144, in <module>
    annotation_set = pd.read_csv(annotation_file)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1087, in read
    df = DataFrame(col_dict, columns=columns, index=index)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 330, in __init__
    mgr = self._init_dict(data, index, columns, dtype=dtype)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 461, in _init_dict
    return _arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/usr/lib/python3/dist-packages/pandas/core/frame.py", line 6173, in _arrays_to_mgr
    return create_block_manager_from_arrays(arrays, arr_names, axes)
  File "/usr/lib/python3/dist-packages/pandas/core/internals.py", line 4637, in create_block_manager_from_arrays
    blocks = form_blocks(arrays, names, axes)
  File "/usr/lib/python3/dist-packages/pandas/core/internals.py", line 4709, in form_blocks
    int_blocks = _multi_blockify(int_items)
  File "/usr/lib/python3/dist-packages/pandas/core/internals.py", line 4778, in _multi_blockify
    values, placement = _stack_arrays(list(tup_block), dtype)
  File "/usr/lib/python3/dist-packages/pandas/core/internals.py", line 4821, in _stack_arrays
    stacked = np.empty(shape, dtype=dtype)
numpy.core._exceptions.MemoryError: Unable to allocate 669. MiB for an array with shape (6, 14610229) and data type int64
user@tx1:/media/user/SD/jetson-inference/python/training/detection/ssd$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/mmcblk0p1  14384136 13063848    569904  96% /
none             1779756        0   1779756   0% /dev
tmpfs            2025108    41768   1983340   3% /dev/shm
tmpfs            2025108    71648   1953460   4% /run
tmpfs               5120        4      5116   1% /run/lock
tmpfs            2025108        0   2025108   0% /sys/fs/cgroup
tmpfs             405020        4    405016   1% /run/user/0
tmpfs             405020       24    404996   1% /run/user/120
tmpfs             405020      148    404872   1% /run/user/1000
/dev/mmcblk2p1  30542260 13082328  15885404  46% /media/user/SD
user@tx1:/media/user/SD/jetson-inference/python/training/detection/ssd$ export TMPDIR=/media/user/SD/temp
user@tx1:/media/user/SD/jetson-inference/python/training/detection/ssd$  python3 open_images_downloader.py --class-names "Apple,Orange,Banana,Strawberry,Grape,Pear,Pineapple,Watermelon" --data=data/fruit
2021-04-25 16:53:50 - Requested 8 classes, found 8 classes
2021-04-25 16:53:50 - Read annotation file data/fruit/train-annotations-bbox.csv
^CTraceback (most recent call last):
  File "open_images_downloader.py", line 144, in <module>
    annotation_set = pd.read_csv(annotation_file)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 455, in _read
    data = parser.read(nrows)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1069, in read
    ret = self._engine.read(nrows)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1839, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 902, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 924, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 1001, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1130, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1175, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1221, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "/usr/lib/python3/dist-packages/pandas/core/dtypes/common.py", line 777, in is_integer_dtype
    def is_integer_dtype(arr_or_dtype):
KeyboardInterrupt
user@tx1:/media/user/SD/jetson-inference/python/training/detection/ssd$  python3 open_images_downloader.py --class-names "Apple" --data=data/fruit
2021-04-25 16:54:50 - Requested 1 classes, found 1 classes
2021-04-25 16:54:50 - Read annotation file data/fruit/train-annotations-bbox.csv
Killed
user@tx1:/media/user/SD/jetson-inference/python/training/detection/ssd$ python3 open_images_downloader.py --stats-only --class-names "Apple,Orange,Banana,Strawberry,Grape,Pear,Pineapple,Watermelon" --data=data/fruit
2021-04-25 16:59:20 - Requested 8 classes, found 8 classes
2021-04-25 16:59:20 - Read annotation file data/fruit/train-annotations-bbox.csv
Killed

```

**Comment by DJT777** [comment]
I was able to solve this by cloning the repository onto my laptop then downloading and transferring the data folder to the jetson.

**Comment by dusty-nv** [comment]
> I was able to solve this by cloning the repository onto my laptop then running the download script and transferring the data folder to the jetson.

OK gotcha - the `Killed` message means that it ran out of memory.   To free up additional memory, you may want to try these suggestions:

* https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-transfer-learning.md#mounting-swap
* https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-transfer-learning.md#disabling-the-desktop-gui
