### ISSUE TITLE
'NoneType' object has no attribute shape - when running train_ssd.py

### ISSUE THREAD

**Issue by DJT777** [dusty-nv/jetson-inference#1026]
Hey Dusty,

I am wondering if you could have a look at this and help me solve it.

I am trying to retrain using your tutorial for retraining mobilenet, but with a single class for birds instead. I used this command on my laptop then transferred over the data to the jetson to the appropriate folder in /media/user/SD/jetson-inference/python/training/detection/ssd. I

`python3 open_images_downloader.py --max-images=5000 --class-names "Bird" --data=/data/bird`

That produced a dataset, but when I went to train I got this error. I am wondering if you will help me figure this one out.

```
user@tx1:/media/user/SD/jetson-inference/python/training/detection/ssd$ python3 train_ssd.py --data=data/bird --model-dir=models/bird --batch-size=4 --epochs=30
2021-04-25 17:30:24 - Using CUDA...
2021-04-25 17:30:24 - Namespace(balance_data=False, base_net=None, base_net_lr=0.001, batch_size=4, checkpoint_folder='models/bird', dataset_type='open_images', datasets=['data/bird'], debug_steps=10, extra_layers_lr=None, freeze_base_net=False, freeze_net=False, gamma=0.1, lr=0.01, mb2_width_mult=1.0, milestones='80,100', momentum=0.9, net='mb1-ssd', num_epochs=30, num_workers=2, pretrained_ssd='models/mobilenet-v1-ssd-mp-0_675.pth', resume=None, scheduler='cosine', t_max=100, use_cuda=True, validation_epochs=1, weight_decay=0.0005)
2021-04-25 17:30:24 - Prepare training datasets.
2021-04-25 17:30:24 - loading annotations from: data/bird/sub-train-annotations-bbox.csv
2021-04-25 17:30:24 - annotations loaded from:  data/bird/sub-train-annotations-bbox.csv
num images:  4338
2021-04-25 17:30:38 - Dataset Summary:Number of Images: 4338
Minimum Number of Images for a Class: -1
Label Distribution:
	Bird: 11700
2021-04-25 17:30:39 - Stored labels into file models/bird/labels.txt.
2021-04-25 17:30:39 - Train dataset size: 4338
2021-04-25 17:30:39 - Prepare Validation datasets.
2021-04-25 17:30:39 - loading annotations from: data/bird/sub-test-annotations-bbox.csv
2021-04-25 17:30:39 - annotations loaded from:  data/bird/sub-test-annotations-bbox.csv
num images:  497
2021-04-25 17:30:40 - Dataset Summary:Number of Images: 497
Minimum Number of Images for a Class: -1
Label Distribution:
	Bird: 695
2021-04-25 17:30:40 - Validation dataset size: 497
2021-04-25 17:30:40 - Build network.
2021-04-25 17:30:40 - Init from pretrained ssd models/mobilenet-v1-ssd-mp-0_675.pth
2021-04-25 17:30:41 - Took 0.49 seconds to load the model.
2021-04-25 17:30:51 - Learning rate: 0.01, Base net learning rate: 0.001, Extra Layers learning rate: 0.01.
2021-04-25 17:30:51 - Uses CosineAnnealingLR scheduler.
2021-04-25 17:30:51 - Start training from epoch 0.
/home/user/.local/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:123: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
Traceback (most recent call last):
  File "train_ssd.py", line 343, in <module>
    device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "train_ssd.py", line 113, in train
    for i, data in enumerate(loader):
  File "/home/user/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/user/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/user/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/user/.local/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/user/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/user/.local/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 207, in __getitem__
    return self.datasets[dataset_idx][sample_idx]
  File "/media/user/SD/jetson-inference/python/training/detection/ssd/vision/datasets/open_images.py", line 46, in __getitem__
    _, image, boxes, labels = self._getitem(index)
  File "/media/user/SD/jetson-inference/python/training/detection/ssd/vision/datasets/open_images.py", line 30, in _getitem
    image = self._read_image(image_info['image_id'])
  File "/media/user/SD/jetson-inference/python/training/detection/ssd/vision/datasets/open_images.py", line 108, in _read_image
    if image.shape[2] == 1:
AttributeError: 'NoneType' object has no attribute 'shape'

```

@dusty-nv 

error when using fruits:
```

user@tx1:/media/user/SD/jetson-inference/python/training/detection/ssd$ python3 train_ssd.py --data=data/fruit --model-dir=models/fruit --batch-size=4 --epochs=30
2021-04-25 18:41:10 - Using CUDA...
2021-04-25 18:41:10 - Namespace(balance_data=False, base_net=None, base_net_lr=0.001, batch_size=4, checkpoint_folder='models/fruit', dataset_type='open_images', datasets=['data/fruit'], debug_steps=10, extra_layers_lr=None, freeze_base_net=False, freeze_net=False, gamma=0.1, lr=0.01, mb2_width_mult=1.0, milestones='80,100', momentum=0.9, net='mb1-ssd', num_epochs=30, num_workers=2, pretrained_ssd='models/mobilenet-v1-ssd-mp-0_675.pth', resume=None, scheduler='cosine', t_max=100, use_cuda=True, validation_epochs=1, weight_decay=0.0005)
2021-04-25 18:41:10 - Prepare training datasets.
2021-04-25 18:41:10 - loading annotations from: data/fruit/sub-train-annotations-bbox.csv
Traceback (most recent call last):
  File "train_ssd.py", line 221, in <module>
    dataset_type="train", balance_data=args.balance_data)
  File "/media/user/SD/jetson-inference/python/training/detection/ssd/vision/datasets/open_images.py", line 19, in __init__
    self.data, self.class_names, self.class_dict = self._read_data()
  File "/media/user/SD/jetson-inference/python/training/detection/ssd/vision/datasets/open_images.py", line 65, in _read_data
    annotations = pd.read_csv(annotation_file)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 709, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 449, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 818, in __init__
    self._make_engine(self.engine)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1049, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/usr/lib/python3/dist-packages/pandas/io/parsers.py", line 1695, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 565, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

```

**Comment by dusty-nv** [comment]
> File "/media/user/SD/jetson-inference/python/training/detection/ssd/vision/datasets/open_images.py", line 30, in _getitem
>     image = self._read_image(image_info['image_id'])
>   File "/media/user/SD/jetson-inference/python/training/detection/ssd/vision/datasets/open_images.py", line 108, in _read_image
>     if image.shape[2] == 1:
> AttributeError: 'NoneType' object has no attribute 'shape'

For some reason, it is failing to load the image file.  And in your fruits example, it seems unable to load the CSV either.  I wonder if perhaps these files got corrupted somehow?

**Comment by DJT777** [comment]
> > File "/media/user/SD/jetson-inference/python/training/detection/ssd/vision/datasets/open_images.py", line 30, in _getitem
> > image = self._read_image(image_info['image_id'])
> > File "/media/user/SD/jetson-inference/python/training/detection/ssd/vision/datasets/open_images.py", line 108, in _read_image
> > if image.shape[2] == 1:
> > AttributeError: 'NoneType' object has no attribute 'shape'
> 
> For some reason, it is failing to load the image file. And in your fruits example, it seems unable to load the CSV either. I wonder if perhaps these files got corrupted somehow?

I think you are right about the corrupted files. To solve it I just ran the jetson-inference .py files from SD on my laptop. 

New issue:
I think I need to make a swap space for extra memory. Can you have a look at the terminal near the bottom and verify if a swap partition would solve that?

```
user@tx1:/media/user/SD/jetson-inference/python/training/detection/ssd$ python3 train_ssd.py --data=data/bird --model-dir=models/bird --batch-size=4 --epochs=30
2021-04-26 13:44:08 - Using CUDA...
2021-04-26 13:44:08 - Namespace(balance_data=False, base_net=None, base_net_lr=0.001, batch_size=4, checkpoint_folder='models/bird', dataset_type='open_images', datasets=['data/bird'], debug_steps=10, extra_layers_lr=None, freeze_base_net=False, freeze_net=False, gamma=0.1, lr=0.01, mb2_width_mult=1.0, milestones='80,100', momentum=0.9, net='mb1-ssd', num_epochs=30, num_workers=2, pretrained_ssd='models/mobilenet-v1-ssd-mp-0_675.pth', resume=None, scheduler='cosine', t_max=100, use_cuda=True, validation_epochs=1, weight_decay=0.0005)
2021-04-26 13:44:08 - Prepare training datasets.
2021-04-26 13:44:08 - loading annotations from: data/bird/sub-train-annotations-bbox.csv
2021-04-26 13:44:08 - annotations loaded from:  data/bird/sub-train-annotations-bbox.csv
num images:  4338
2021-04-26 13:44:23 - Dataset Summary:Number of Images: 4338
Minimum Number of Images for a Class: -1
Label Distribution:
	Bird: 11316
2021-04-26 13:44:23 - Stored labels into file models/bird/labels.txt.
2021-04-26 13:44:23 - Train dataset size: 4338
2021-04-26 13:44:23 - Prepare Validation datasets.
2021-04-26 13:44:23 - loading annotations from: data/bird/sub-test-annotations-bbox.csv
2021-04-26 13:44:23 - annotations loaded from:  data/bird/sub-test-annotations-bbox.csv
num images:  497
2021-04-26 13:44:25 - Dataset Summary:Number of Images: 497
Minimum Number of Images for a Class: -1
Label Distribution:
	Bird: 685
2021-04-26 13:44:25 - Validation dataset size: 497
2021-04-26 13:44:25 - Build network.
2021-04-26 13:44:25 - Init from pretrained ssd models/mobilenet-v1-ssd-mp-0_675.pth
2021-04-26 13:44:26 - Took 0.50 seconds to load the model.
2021-04-26 13:44:36 - Learning rate: 0.01, Base net learning rate: 0.001, Extra Layers learning rate: 0.01.
2021-04-26 13:44:36 - Uses CosineAnnealingLR scheduler.
2021-04-26 13:44:36 - Start training from epoch 0.
/home/user/.local/lib/python3.6/site-packages/torch/optim/lr_scheduler.py:123: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/home/user/.local/lib/python3.6/site-packages/torch/nn/_reduction.py:44: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
2021-04-26 13:45:06 - Epoch: 0, Step: 10/1085, Avg Loss: 9.6001, Avg Regression Loss 4.5722, Avg Classification Loss: 5.0279
2021-04-26 13:45:11 - Epoch: 0, Step: 20/1085, Avg Loss: 6.1991, Avg Regression Loss 2.9636, Avg Classification Loss: 3.2354
2021-04-26 13:45:19 - Epoch: 0, Step: 30/1085, Avg Loss: 5.2272, Avg Regression Loss 2.4967, Avg Classification Loss: 2.7305
2021-04-26 13:45:24 - Epoch: 0, Step: 40/1085, Avg Loss: 7.3053, Avg Regression Loss 4.0042, Avg Classification Loss: 3.3011
2021-04-26 13:45:30 - Epoch: 0, Step: 50/1085, Avg Loss: 5.3907, Avg Regression Loss 2.4520, Avg Classification Loss: 2.9387
2021-04-26 13:45:35 - Epoch: 0, Step: 60/1085, Avg Loss: 5.3235, Avg Regression Loss 2.4364, Avg Classification Loss: 2.8872
2021-04-26 13:45:43 - Epoch: 0, Step: 70/1085, Avg Loss: 5.4156, Avg Regression Loss 2.7165, Avg Classification Loss: 2.6991
2021-04-26 13:45:48 - Epoch: 0, Step: 80/1085, Avg Loss: 5.6360, Avg Regression Loss 2.7837, Avg Classification Loss: 2.8523
2021-04-26 13:45:54 - Epoch: 0, Step: 90/1085, Avg Loss: 5.2191, Avg Regression Loss 2.4698, Avg Classification Loss: 2.7494
2021-04-26 13:45:59 - Epoch: 0, Step: 100/1085, Avg Loss: 5.2288, Avg Regression Loss 2.5967, Avg Classification Loss: 2.6321
2021-04-26 13:46:06 - Epoch: 0, Step: 110/1085, Avg Loss: 4.3076, Avg Regression Loss 1.8530, Avg Classification Loss: 2.4546
2021-04-26 13:46:11 - Epoch: 0, Step: 120/1085, Avg Loss: 4.9160, Avg Regression Loss 2.3414, Avg Classification Loss: 2.5746
2021-04-26 13:46:16 - Epoch: 0, Step: 130/1085, Avg Loss: 4.8301, Avg Regression Loss 2.1542, Avg Classification Loss: 2.6758
2021-04-26 13:46:21 - Epoch: 0, Step: 140/1085, Avg Loss: 5.1814, Avg Regression Loss 2.4598, Avg Classification Loss: 2.7216
2021-04-26 13:46:29 - Epoch: 0, Step: 150/1085, Avg Loss: 4.9651, Avg Regression Loss 2.4226, Avg Classification Loss: 2.5425
2021-04-26 13:46:38 - Epoch: 0, Step: 160/1085, Avg Loss: 5.0709, Avg Regression Loss 2.6891, Avg Classification Loss: 2.3817
2021-04-26 13:46:43 - Epoch: 0, Step: 170/1085, Avg Loss: 4.5506, Avg Regression Loss 2.0874, Avg Classification Loss: 2.4632
2021-04-26 13:46:48 - Epoch: 0, Step: 180/1085, Avg Loss: 4.4122, Avg Regression Loss 2.0205, Avg Classification Loss: 2.3916
2021-04-26 13:46:53 - Epoch: 0, Step: 190/1085, Avg Loss: 4.2414, Avg Regression Loss 1.7151, Avg Classification Loss: 2.5263
2021-04-26 13:46:58 - Epoch: 0, Step: 200/1085, Avg Loss: 4.6083, Avg Regression Loss 2.2559, Avg Classification Loss: 2.3524
2021-04-26 13:47:03 - Epoch: 0, Step: 210/1085, Avg Loss: 4.8579, Avg Regression Loss 2.3632, Avg Classification Loss: 2.4947
2021-04-26 13:47:08 - Epoch: 0, Step: 220/1085, Avg Loss: 4.3755, Avg Regression Loss 1.9874, Avg Classification Loss: 2.3881
2021-04-26 13:47:13 - Epoch: 0, Step: 230/1085, Avg Loss: 4.3889, Avg Regression Loss 1.8602, Avg Classification Loss: 2.5287
2021-04-26 13:47:18 - Epoch: 0, Step: 240/1085, Avg Loss: 4.5225, Avg Regression Loss 1.9723, Avg Classification Loss: 2.5502
2021-04-26 13:47:23 - Epoch: 0, Step: 250/1085, Avg Loss: 4.5611, Avg Regression Loss 2.0888, Avg Classification Loss: 2.4723
2021-04-26 13:47:28 - Epoch: 0, Step: 260/1085, Avg Loss: 4.5287, Avg Regression Loss 2.0321, Avg Classification Loss: 2.4966
2021-04-26 13:47:33 - Epoch: 0, Step: 270/1085, Avg Loss: 5.1169, Avg Regression Loss 2.7160, Avg Classification Loss: 2.4009
2021-04-26 13:47:38 - Epoch: 0, Step: 280/1085, Avg Loss: 4.4290, Avg Regression Loss 2.1145, Avg Classification Loss: 2.3145
2021-04-26 13:47:44 - Epoch: 0, Step: 290/1085, Avg Loss: 5.0486, Avg Regression Loss 2.5462, Avg Classification Loss: 2.5023
2021-04-26 13:47:50 - Epoch: 0, Step: 300/1085, Avg Loss: 4.3778, Avg Regression Loss 2.1744, Avg Classification Loss: 2.2034
2021-04-26 13:47:55 - Epoch: 0, Step: 310/1085, Avg Loss: 4.5534, Avg Regression Loss 2.2322, Avg Classification Loss: 2.3212
2021-04-26 13:48:00 - Epoch: 0, Step: 320/1085, Avg Loss: 4.7547, Avg Regression Loss 2.2076, Avg Classification Loss: 2.5470
2021-04-26 13:48:05 - Epoch: 0, Step: 330/1085, Avg Loss: 4.2095, Avg Regression Loss 1.9770, Avg Classification Loss: 2.2325
2021-04-26 13:48:10 - Epoch: 0, Step: 340/1085, Avg Loss: 3.9722, Avg Regression Loss 1.7777, Avg Classification Loss: 2.1945
2021-04-26 13:48:16 - Epoch: 0, Step: 350/1085, Avg Loss: 4.7459, Avg Regression Loss 2.3230, Avg Classification Loss: 2.4229
2021-04-26 13:48:21 - Epoch: 0, Step: 360/1085, Avg Loss: 4.0757, Avg Regression Loss 1.8850, Avg Classification Loss: 2.1907
2021-04-26 13:48:26 - Epoch: 0, Step: 370/1085, Avg Loss: 4.0406, Avg Regression Loss 1.6013, Avg Classification Loss: 2.4394
2021-04-26 13:48:31 - Epoch: 0, Step: 380/1085, Avg Loss: 3.9503, Avg Regression Loss 1.6295, Avg Classification Loss: 2.3209
2021-04-26 13:48:36 - Epoch: 0, Step: 390/1085, Avg Loss: 4.0739, Avg Regression Loss 1.6076, Avg Classification Loss: 2.4663
2021-04-26 13:48:41 - Epoch: 0, Step: 400/1085, Avg Loss: 4.1262, Avg Regression Loss 1.8380, Avg Classification Loss: 2.2881
2021-04-26 13:48:52 - Epoch: 0, Step: 410/1085, Avg Loss: 4.9849, Avg Regression Loss 2.5934, Avg Classification Loss: 2.3915
2021-04-26 13:48:57 - Epoch: 0, Step: 420/1085, Avg Loss: 4.1978, Avg Regression Loss 1.8370, Avg Classification Loss: 2.3609
2021-04-26 13:49:02 - Epoch: 0, Step: 430/1085, Avg Loss: 4.9217, Avg Regression Loss 2.6401, Avg Classification Loss: 2.2815
2021-04-26 13:49:07 - Epoch: 0, Step: 440/1085, Avg Loss: 3.9731, Avg Regression Loss 1.6973, Avg Classification Loss: 2.2757
2021-04-26 13:49:12 - Epoch: 0, Step: 450/1085, Avg Loss: 4.5098, Avg Regression Loss 2.0381, Avg Classification Loss: 2.4717
2021-04-26 13:49:17 - Epoch: 0, Step: 460/1085, Avg Loss: 3.8267, Avg Regression Loss 1.5281, Avg Classification Loss: 2.2985
2021-04-26 13:49:21 - Epoch: 0, Step: 470/1085, Avg Loss: 4.0996, Avg Regression Loss 1.7631, Avg Classification Loss: 2.3365
2021-04-26 13:49:27 - Epoch: 0, Step: 480/1085, Avg Loss: 4.4329, Avg Regression Loss 2.0299, Avg Classification Loss: 2.4031
2021-04-26 13:49:32 - Epoch: 0, Step: 490/1085, Avg Loss: 4.5241, Avg Regression Loss 2.0586, Avg Classification Loss: 2.4656
2021-04-26 13:49:36 - Epoch: 0, Step: 500/1085, Avg Loss: 5.3465, Avg Regression Loss 2.8553, Avg Classification Loss: 2.4912
2021-04-26 13:49:41 - Epoch: 0, Step: 510/1085, Avg Loss: 4.0580, Avg Regression Loss 1.6651, Avg Classification Loss: 2.3930
2021-04-26 13:49:47 - Epoch: 0, Step: 520/1085, Avg Loss: 4.0664, Avg Regression Loss 1.7352, Avg Classification Loss: 2.3312
2021-04-26 13:49:53 - Epoch: 0, Step: 530/1085, Avg Loss: 4.4979, Avg Regression Loss 2.1791, Avg Classification Loss: 2.3188
2021-04-26 13:49:58 - Epoch: 0, Step: 540/1085, Avg Loss: 4.9604, Avg Regression Loss 2.5453, Avg Classification Loss: 2.4151
2021-04-26 13:50:03 - Epoch: 0, Step: 550/1085, Avg Loss: 4.3208, Avg Regression Loss 1.9522, Avg Classification Loss: 2.3686
2021-04-26 13:50:08 - Epoch: 0, Step: 560/1085, Avg Loss: 4.3994, Avg Regression Loss 1.9510, Avg Classification Loss: 2.4484
2021-04-26 13:50:13 - Epoch: 0, Step: 570/1085, Avg Loss: 4.3519, Avg Regression Loss 1.9637, Avg Classification Loss: 2.3882
2021-04-26 13:50:18 - Epoch: 0, Step: 580/1085, Avg Loss: 4.7398, Avg Regression Loss 2.2300, Avg Classification Loss: 2.5097
2021-04-26 13:50:23 - Epoch: 0, Step: 590/1085, Avg Loss: 4.2662, Avg Regression Loss 1.9840, Avg Classification Loss: 2.2822
2021-04-26 13:50:28 - Epoch: 0, Step: 600/1085, Avg Loss: 4.2035, Avg Regression Loss 1.9642, Avg Classification Loss: 2.2393
2021-04-26 13:50:32 - Epoch: 0, Step: 610/1085, Avg Loss: 3.8971, Avg Regression Loss 1.5946, Avg Classification Loss: 2.3024
2021-04-26 13:50:37 - Epoch: 0, Step: 620/1085, Avg Loss: 4.5673, Avg Regression Loss 2.2514, Avg Classification Loss: 2.3159
2021-04-26 13:50:42 - Epoch: 0, Step: 630/1085, Avg Loss: 4.4249, Avg Regression Loss 1.8756, Avg Classification Loss: 2.5493
2021-04-26 13:50:49 - Epoch: 0, Step: 640/1085, Avg Loss: 4.0255, Avg Regression Loss 1.7551, Avg Classification Loss: 2.2704
2021-04-26 13:50:54 - Epoch: 0, Step: 650/1085, Avg Loss: 4.6475, Avg Regression Loss 2.2543, Avg Classification Loss: 2.3932
2021-04-26 13:50:59 - Epoch: 0, Step: 660/1085, Avg Loss: 3.6175, Avg Regression Loss 1.5034, Avg Classification Loss: 2.1142
2021-04-26 13:51:04 - Epoch: 0, Step: 670/1085, Avg Loss: 3.4619, Avg Regression Loss 1.4287, Avg Classification Loss: 2.0331
2021-04-26 13:51:09 - Epoch: 0, Step: 680/1085, Avg Loss: 4.4424, Avg Regression Loss 2.0413, Avg Classification Loss: 2.4011
2021-04-26 13:51:14 - Epoch: 0, Step: 690/1085, Avg Loss: 4.3349, Avg Regression Loss 1.9227, Avg Classification Loss: 2.4121
2021-04-26 13:51:19 - Epoch: 0, Step: 700/1085, Avg Loss: 3.6246, Avg Regression Loss 1.3941, Avg Classification Loss: 2.2304
2021-04-26 13:51:24 - Epoch: 0, Step: 710/1085, Avg Loss: 3.9675, Avg Regression Loss 1.7562, Avg Classification Loss: 2.2113
2021-04-26 13:51:29 - Epoch: 0, Step: 720/1085, Avg Loss: 3.6006, Avg Regression Loss 1.4922, Avg Classification Loss: 2.1084
2021-04-26 13:51:34 - Epoch: 0, Step: 730/1085, Avg Loss: 3.6561, Avg Regression Loss 1.5580, Avg Classification Loss: 2.0982
2021-04-26 13:51:39 - Epoch: 0, Step: 740/1085, Avg Loss: 3.9608, Avg Regression Loss 1.5995, Avg Classification Loss: 2.3613
2021-04-26 13:51:44 - Epoch: 0, Step: 750/1085, Avg Loss: 3.5421, Avg Regression Loss 1.5119, Avg Classification Loss: 2.0302
2021-04-26 13:51:49 - Epoch: 0, Step: 760/1085, Avg Loss: 4.1550, Avg Regression Loss 1.7138, Avg Classification Loss: 2.4411
2021-04-26 13:51:54 - Epoch: 0, Step: 770/1085, Avg Loss: 3.5333, Avg Regression Loss 1.4304, Avg Classification Loss: 2.1029
2021-04-26 13:51:59 - Epoch: 0, Step: 780/1085, Avg Loss: 4.5342, Avg Regression Loss 2.1108, Avg Classification Loss: 2.4234
2021-04-26 13:52:04 - Epoch: 0, Step: 790/1085, Avg Loss: 3.5925, Avg Regression Loss 1.5172, Avg Classification Loss: 2.0753
2021-04-26 13:52:09 - Epoch: 0, Step: 800/1085, Avg Loss: 4.7455, Avg Regression Loss 2.4476, Avg Classification Loss: 2.2978
2021-04-26 13:52:14 - Epoch: 0, Step: 810/1085, Avg Loss: 6.3005, Avg Regression Loss 3.8419, Avg Classification Loss: 2.4586
2021-04-26 13:52:22 - Epoch: 0, Step: 820/1085, Avg Loss: 4.1696, Avg Regression Loss 1.8411, Avg Classification Loss: 2.3284
2021-04-26 13:52:27 - Epoch: 0, Step: 830/1085, Avg Loss: 4.4525, Avg Regression Loss 2.1188, Avg Classification Loss: 2.3337
2021-04-26 13:52:32 - Epoch: 0, Step: 840/1085, Avg Loss: 4.3667, Avg Regression Loss 1.9920, Avg Classification Loss: 2.3747
2021-04-26 13:52:37 - Epoch: 0, Step: 850/1085, Avg Loss: 4.2840, Avg Regression Loss 1.9739, Avg Classification Loss: 2.3100
2021-04-26 13:52:42 - Epoch: 0, Step: 860/1085, Avg Loss: 4.2804, Avg Regression Loss 1.8904, Avg Classification Loss: 2.3899
2021-04-26 13:52:47 - Epoch: 0, Step: 870/1085, Avg Loss: 5.7986, Avg Regression Loss 3.1649, Avg Classification Loss: 2.6336
2021-04-26 13:52:52 - Epoch: 0, Step: 880/1085, Avg Loss: 3.8115, Avg Regression Loss 1.5360, Avg Classification Loss: 2.2755
2021-04-26 13:52:57 - Epoch: 0, Step: 890/1085, Avg Loss: 3.6407, Avg Regression Loss 1.4639, Avg Classification Loss: 2.1768
2021-04-26 13:53:03 - Epoch: 0, Step: 900/1085, Avg Loss: 4.0323, Avg Regression Loss 1.7031, Avg Classification Loss: 2.3292
2021-04-26 13:53:08 - Epoch: 0, Step: 910/1085, Avg Loss: 3.1533, Avg Regression Loss 1.2224, Avg Classification Loss: 1.9309
2021-04-26 13:53:13 - Epoch: 0, Step: 920/1085, Avg Loss: 4.9594, Avg Regression Loss 2.5556, Avg Classification Loss: 2.4038
2021-04-26 13:53:18 - Epoch: 0, Step: 930/1085, Avg Loss: 4.6040, Avg Regression Loss 2.2799, Avg Classification Loss: 2.3241
2021-04-26 13:53:23 - Epoch: 0, Step: 940/1085, Avg Loss: 3.6444, Avg Regression Loss 1.3979, Avg Classification Loss: 2.2465
2021-04-26 13:53:28 - Epoch: 0, Step: 950/1085, Avg Loss: 4.0856, Avg Regression Loss 1.7644, Avg Classification Loss: 2.3212
2021-04-26 13:53:33 - Epoch: 0, Step: 960/1085, Avg Loss: 3.9032, Avg Regression Loss 1.6559, Avg Classification Loss: 2.2474
2021-04-26 13:53:38 - Epoch: 0, Step: 970/1085, Avg Loss: 4.2126, Avg Regression Loss 2.0044, Avg Classification Loss: 2.2083
2021-04-26 13:53:43 - Epoch: 0, Step: 980/1085, Avg Loss: 3.4943, Avg Regression Loss 1.3956, Avg Classification Loss: 2.0987
2021-04-26 13:53:48 - Epoch: 0, Step: 990/1085, Avg Loss: 4.7913, Avg Regression Loss 2.3557, Avg Classification Loss: 2.4356
2021-04-26 13:53:53 - Epoch: 0, Step: 1000/1085, Avg Loss: 3.7858, Avg Regression Loss 1.5304, Avg Classification Loss: 2.2555
2021-04-26 13:53:58 - Epoch: 0, Step: 1010/1085, Avg Loss: 4.7938, Avg Regression Loss 2.4208, Avg Classification Loss: 2.3730
2021-04-26 13:54:03 - Epoch: 0, Step: 1020/1085, Avg Loss: 3.7709, Avg Regression Loss 1.4484, Avg Classification Loss: 2.3225
2021-04-26 13:54:08 - Epoch: 0, Step: 1030/1085, Avg Loss: 3.8048, Avg Regression Loss 1.4686, Avg Classification Loss: 2.3362
2021-04-26 13:54:13 - Epoch: 0, Step: 1040/1085, Avg Loss: 3.4590, Avg Regression Loss 1.3730, Avg Classification Loss: 2.0860
2021-04-26 13:54:18 - Epoch: 0, Step: 1050/1085, Avg Loss: 4.4341, Avg Regression Loss 2.0990, Avg Classification Loss: 2.3352
2021-04-26 13:54:23 - Epoch: 0, Step: 1060/1085, Avg Loss: 3.9658, Avg Regression Loss 1.6685, Avg Classification Loss: 2.2973
2021-04-26 13:54:28 - Epoch: 0, Step: 1070/1085, Avg Loss: 3.8129, Avg Regression Loss 1.7751, Avg Classification Loss: 2.0379
2021-04-26 13:54:33 - Epoch: 0, Step: 1080/1085, Avg Loss: 4.1181, Avg Regression Loss 1.9384, Avg Classification Loss: 2.1797
2021-04-26 13:54:56 - Epoch: 0, Validation Loss: 3.1963, Validation Regression Loss 1.2421, Validation Classification Loss: 1.9543
2021-04-26 13:54:56 - Saved model models/bird/mb1-ssd-Epoch-0-Loss-3.196309384346008.pth
Traceback (most recent call last):
  File "train_ssd.py", line 343, in <module>
    device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "train_ssd.py", line 113, in train
    for i, data in enumerate(loader):
  File "/home/user/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 291, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/home/user/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 737, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

```

**Comment by dusty-nv** [comment]
> OSError: [Errno 12] Cannot allocate memory

Yes, if you are running out of memory, try these suggestions:

* https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-transfer-learning.md#mounting-swap
* https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-transfer-learning.md#disabling-the-desktop-gui
* run `train_ssd.py` with `--batch-size=1` and `--workers=1`
