### ISSUE TITLE
no module named torchvision 

### ISSUE THREAD

**Issue by ManlaiB** [dusty-nv/jetson-inference#1087]
i already downloaded torch by ./install-pytorch.sh command and then I created my own dataset. 
when i run a train command i met this issue. How can i solve this issue. 

train_ssd.py --dataset-type=voc --data=data/fire --model-dir=models/fire
Traceback (most recent call last):
  File "train_ssd.py", line 16, in <module>
    from vision.ssd.vgg_ssd import create_vgg_ssd
  File "/home/jetson/jetson-inference/python/training/detection/ssd/vision/ssd/vgg_ssd.py", line 6, in <module>
    from .predictor import Predictor
  File "/home/jetson/jetson-inference/python/training/detection/ssd/vision/ssd/predictor.py", line 4, in <module>
    from .data_preprocessing import PredictionTransform
  File "/home/jetson/jetson-inference/python/training/detection/ssd/vision/ssd/data_preprocessing.py", line 1, in <module>
    from ..transforms.transforms import *
  File "/home/jetson/jetson-inference/python/training/detection/ssd/vision/transforms/transforms.py", line 5, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'

**Comment by dusty-nv** [comment]
Hi, if you run a python3 interpreter, can you 'import torchvision'?

Can you try running the container which already has these packages installed?
________________________________
From: ManlaiB ***@***.***>
Sent: Thursday, June 3, 2021 9:40:19 PM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] no module named torchvision (#1087)


i already downloaded torch by ./install-pytorch.sh command and then I created my own dataset.
when i run a train command i met this issue. How can i solve this issue.

train_ssd.py --dataset-type=voc --data=data/fire --model-dir=models/fire
Traceback (most recent call last):
File "train_ssd.py", line 16, in
from vision.ssd.vgg_ssd import create_vgg_ssd
File "/home/jetson/jetson-inference/python/training/detection/ssd/vision/ssd/vgg_ssd.py", line 6, in
from .predictor import Predictor
File "/home/jetson/jetson-inference/python/training/detection/ssd/vision/ssd/predictor.py", line 4, in
from .data_preprocessing import PredictionTransform
File "/home/jetson/jetson-inference/python/training/detection/ssd/vision/ssd/data_preprocessing.py", line 1, in
from ..transforms.transforms import *
File "/home/jetson/jetson-inference/python/training/detection/ssd/vision/transforms/transforms.py", line 5, in
from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'
