### ISSUE TITLE
Error while executing segNet example

### ISSUE THREAD

**Issue by NicolasBilberry** [dusty-nv/jetson-inference#115]
Hello there !

I'm trying to execute the segNet example on my host machine (Ubuntu 16.04) with TensorRT v2.1 and a pre-trained model but I get this error : 
`[GIE]  attempting to open cache file snapshot_iter_27132.caffemodel.2.tensorcache`
`[GIE]  cache file not found, profiling network model`
`terminate called after throwing an instance of 'nvinfer1::CudaError'`
`  what():  std::exception`
`Aborted (core dumped)`

Any idea what I did wrong ?

Thanks a lot !

**Comment by NicolasBilberry** [comment]
Here's the gdb backtrace, if it could be of any use : 

```
#0  0x00007ffff715f428 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:54
        resultvar = 0
        pid = 27253
        selftid = 27253
#1  0x00007ffff716102a in __GI_abort () at abort.c:89
        save_stage = 2
        act = {__sigaction_handler = {sa_handler = 0x0, sa_sigaction = 0x0}, sa_mask = {__val = {0, 140737342534976, 140737339075583, 140737342534976, 1, 10, 140737339593360, 10, 140737342539632, 
              140737353885392, 140737339593360, 1, 140737353887888, 8422288, 140737342539632, 140737353885568}}, sa_flags = -288061312, sa_restorer = 0x7fffeedf2029}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007fffeed4b84d in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#3  0x00007fffeed496b6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#4  0x00007fffeed49701 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#5  0x00007fffeed49919 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#6  0x00007ffff0fe15e8 in nvinfer1::throwCudaError(char const*, char const*, int, int, char const*) () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.3
No symbol table info available.
#7  0x00007ffff0fe2f6d in nvinfer1::cudnn::hasNativeFp16() () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.3
No symbol table info available.
#8  0x00007ffff1001e07 in nvinfer1::cudnn::HardwareContext::HardwareContext() () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.3
No symbol table info available.
#9  0x00007ffff0ffcd25 in createInferBuilder_INTERNAL () from /usr/lib/x86_64-linux-gnu/libnvinfer.so.3
No symbol table info available.
#10 0x00007ffff7516289 in nvinfer1::(anonymous namespace)::createInferBuilder(nvinfer1::ILogger&) () from /home/poudlard/TensorRT/2.1/jetson-inference-master/build/x86_64/lib/libjetson-inference.so
No symbol table info available.
#11 0x00007ffff7516613 in tensorNet::ProfileModel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int, std::ostream&) () from /home/poudlard/TensorRT/2.1/jetson-inference-master/build/x86_64/lib/libjetson-inference.so
No symbol table info available.
#12 0x00007ffff7516d43 in tensorNet::LoadNetwork(char const*, char const*, char const*, char const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int) ()
   from /home/poudlard/TensorRT/2.1/jetson-inference-master/build/x86_64/lib/libjetson-inference.so
No symbol table info available.
#13 0x00007ffff7514c96 in segNet::Create(char const*, char const*, char const*, char const*, char const*, char const*, unsigned int) ()
   from /home/poudlard/TensorRT/2.1/jetson-inference-master/build/x86_64/lib/libjetson-inference.so
No symbol table info available.
#14 0x00007ffff7514aaa in segNet::Create(int, char**) () from /home/poudlard/TensorRT/2.1/jetson-inference-master/build/x86_64/lib/libjetson-inference.so
No symbol table info available.
#15 0x0000000000403140 in ?? ()
No symbol table info available.
#16 0x00007fffffffdbe8 in ?? ()
No symbol table info available.
#17 0x00000007f7164299 in ?? ()
No symbol table info available.
#18 0x00000000004043c3 in ?? ()
No symbol table info available.
#19 0x0000000700000014 in ?? ()
No symbol table info available.

```

**Comment by NicolasBilberry** [comment]
Solved.
I had an issue with Nvidia's drivers.
Solution : Reinstall + reboot.
