### ISSUE TITLE
Training SSD Mobilenet model outside and importing to run in Jetson Nano 2GB

### ISSUE THREAD

**Issue by Nikil-Shyamsunder** [dusty-nv/jetson-inference#1343]
@Dustin,

I downloaded a subset of classes and am training in my Jetson Nano.  There are about 17000 images across 6 classes.  It is taking about 50 minutes per epoch with a batch size of 4.  That mean it will take me about 30 hours.  That's a long time. 

My questions are:

1) Is there anything else I can do to speed up in my nano?

2) Is there any way to train SSD mobilnet  model outside, say in AWS, using a bigger and faster computer?

3) I tried doing in AWS ubuntu. I tried running the container and I also tried building the environment from scratch.  It fails due to architecture.  Any ideas?  Is this not compatible?

4) If we do train somewhere else, how do I do it with the current scripts?

5) Once I train outside, can I simply bring the model directory and run the command $ python3 onnx_export.py --model-dir=models/mymodel

Please advise.

**Comment by dusty-nv** [comment]
Hi @Nikil-Shyamsunder, you can read some of my response to your question in this thread here:  https://forums.developer.nvidia.com/t/please-help-nvidia-jetson-2gb-training-fails-typeerror-init-missing-1-required-positional-argument-dtype/201674/7?u=dusty_nv

It should be possible run in AWS GPU instance, but I haven't done it myself with AWS.  I have an Ubuntu laptop here that I use.  

You would not use the jetson-inference container on x86, rather you would use a container like the [NGC PyTorch container](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) (which are built for x86).  Then mount/run the [pytorch-ssd repo](https://github.com/dusty-nv/pytorch-ssd) and run train_ssd.py like you normally would.

Regarding the ONNX export, you can do that either on the x86 machine or on your Jetson.

**Comment by Nikil-Shyamsunder** [comment]
Dustin,

I launched a VM in AWS.  Installed boto3, pytorch, opencv etc.  Downloaded  pytorch-ssd repo and ran train_ssd.py like you normally would.  The paaremeters are updated, so made some changes, this is the best i could do:


```
$ python ./train_ssd.py --datasets=data/fruit --checkpoint_folder=models/fruit --batch_size=4 --num_epochs=30

2022-01-27 19:13:01,332 - root - INFO - Namespace(dataset_type='voc', datasets=['data/fruit'], validation_dataset=None, balance_data=False, net='vgg16-ssd', freeze_base_net=False, freeze_net=False, mb2_width_mult=1.0, lr=0.001, momentum=0.9, weight_decay=0.0005, gamma=0.1, base_net_lr=None, extra_layers_lr=None, base_net=None, pretrained_ssd=None, resume=None, scheduler='multi-step', milestones='80,100', t_max=120, batch_size=4, num_epochs=30, num_workers=4, validation_epochs=5, debug_steps=100, use_cuda=True, checkpoint_folder='models/fruit')
2022-01-27 19:13:01,333 - root - INFO - Prepare training datasets.
Traceback (most recent call last):
  File "/home/ec2-user/pytorch-ssd/./train_ssd.py", line 210, in <module>
    dataset = VOCDataset(dataset_path, transform=train_transform,
  File "/home/ec2-user/pytorch-ssd/vision/datasets/voc_dataset.py", line 24, in __init__
    self.ids = VOCDataset._read_image_ids(image_sets_file)
  File "/home/ec2-user/pytorch-ssd/vision/datasets/voc_dataset.py", line 87, in _read_image_ids
    with open(image_sets_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/fruit/ImageSets/Main/trainval.txt'
```

Thoughts?

**Comment by dusty-nv** [comment]
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'data/fruit/ImageSets/Main/trainval.txt'
> ```
> 
> 
>     
>   
> 
> Thoughts?  I know I am not using VOC.

Hmm I'm not sure why it would default to VOC when the default dataset type is open_images:   https://github.com/dusty-nv/pytorch-ssd/blob/8ed842a408f8c4a8812f430cf8063e0b93a56803/train_ssd.py#L33

Can you try specifying `--dataset-type=open_images` ?

**Comment by Nikil-Shyamsunder** [comment]
# Tried --dataset_type=open_images
```
$ ./train_ssd.py --datasets=data/fruit --checkpoint_folder=models/fruit --batch_size=4 --num_epochs=30  --dataset_type=open_images
2022-01-27 20:10:40,070 - root - INFO - Namespace(dataset_type='open_images', datasets=['data/fruit'], validation_dataset=None, balance_data=False, net='vgg16-ssd', freeze_base_net=False, freeze_net=False, mb2_width_mult=1.0, lr=0.001, momentum=0.9, weight_decay=0.0005, gamma=0.1, base_net_lr=None, extra_layers_lr=None, base_net=None, pretrained_ssd=None, resume=None, scheduler='multi-step', milestones='80,100', t_max=120, batch_size=4, num_epochs=30, num_workers=4, validation_epochs=5, debug_steps=100, use_cuda=True, checkpoint_folder='models/fruit')
2022-01-27 20:10:40,072 - root - INFO - Prepare training datasets.
Traceback (most recent call last):
  File "/home/ec2-user/pytorch-ssd/./train_ssd.py", line 220, in <module>
    store_labels(label_file, dataset.class_names)
  File "/home/ec2-user/pytorch-ssd/vision/utils/misc.py", line 44, in store_labels
    with open(path, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'models/fruit/open-images-model-labels.txt'
```

I noticed the default net is vgg16-ssd.  Should it be something else?
```
parser.add_argument('--net', default="vgg16-ssd",
                    help="The network architecture, it can be mb1-ssd, mb1-lite-ssd, mb2-ssd-lite, mb3-large-ssd-lite, mb3-small-ssd-lite or vgg16-ssd.")
```

**Comment by dusty-nv** [comment]
The default `--net` should be mb1-ssd:  https://github.com/dusty-nv/pytorch-ssd/blob/8ed842a408f8c4a8812f430cf8063e0b93a56803/train_ssd.py#L40

Does yours show differently?

**Comment by Nikil-Shyamsunder** [comment]
Dustin, 

You caught the error.  I had clones the other repo.  I should have clones yours.  It is working like a charm.

THANK YOU.  I am loving the jetson nano.

RESOLVED.

**Comment by dusty-nv** [comment]
Aha, ok gotcha - great to hear!  Glad you got it working :)
