### ISSUE TITLE
Error importing jetson-inference: "ImportError: libnvinfer.so.7: cannot open shared object file"

### ISSUE THREAD

**Issue by firststep-dev** [dusty-nv/jetson-inference#1371]
I have just upgraded Jetpack:

```
$ sudo apt show -a nvidia-jetpack
Package: nvidia-jetpack
Version: 4.6-b197
Priority: standard
Section: metapackages
Maintainer: NVIDIA Corporation
Installed-Size: 199 kB
Depends: nvidia-cuda (= 4.6-b197), nvidia-opencv (= 4.6-b197), nvidia-cudnn8 (= 4.6-b197), nvidia-tensorrt (= 4.6-b197), nvidia-visionworks (= 4.6-b197), nvidia-container (= 4.6-b197), nvidia-vpi (= 4.6-b197), nvidia-l4t-jetson-multimedia-api (>> 32.6-0), nvidia-l4t-jetson-multimedia-api (<< 32.7-0)
Homepage: http://developer.nvidia.com/jetson
Download-Size: 29.4 kB
APT-Sources: https://repo.download.nvidia.com/jetson/t194 r32.6/main arm64 Packages
Description: NVIDIA Jetpack Meta Package
```

I get the following error when I run: import jetson.inference.

```
Traceback (most recent call last):
  File "code/run_once/002_run_once_tf2.py", line 1, in <module>
    import utils;
  File "/home/firststep/firststep/code/run_once/utils.py", line 4, in <module>
    import sys; sys.path.insert(0, '/home/firststep/firststep/code/utils'); import firststep_utils as utils;
  File "/home/firststep/firststep/code/utils/firststep_utils.py", line 1, in <module>
    import jetson.inference
  File "/usr/lib/python3.6/dist-packages/jetson/inference/__init__.py", line 8, in <module>
    from jetson_inference_python import *
ImportError: libnvinfer.so.7: cannot open shared object file: No such file or directory
```

I didn't get this error before upgrading Jetpack.

System information (jtop):

![image](https://user-images.githubusercontent.com/82156211/155307867-f9e216cc-904d-460d-aad5-0cda6d435473.png)

What could be the issue here?

**Comment by firststep-dev** [comment]
It seems the the version of jetpack is different between:

`sudo apt show -a nvidia-jetpack`

and
 
`jtop`

**Comment by firststep-dev** [comment]
@dusty-nv - Might you have any idea how I can fix this and safely import jetson.inference?

**Comment by firststep-dev** [comment]
Thanks @dusty-nv that works well.
