### ISSUE TITLE
train_ssd.py - Could not find image ERROR

### ISSUE THREAD

**Issue by julian998-dot** [dusty-nv/jetson-inference#1387]
Hi Dusy!
I followed your video about object detection and i used the tool to create the dataset on voc format to test it and all good! but when i create my real dataset on the PC with the VOC format it shows me this:
```
python3 train_ssd.py  --dataset-type=voc --data=data/Dataset/ --model-dir=models/Dataset/ --batch-size=3 --workers=2 --epochs=30
2022-03-16 01:54:01 - Using CUDA...
2022-03-16 01:54:01 - Namespace(balance_data=False, base_net=None, base_net_lr=0.001, batch_size=3, checkpoint_folder='models/Dataset/', dataset_type='voc', datasets=['data/Dataset/'], debug_steps=10, extra_layers_lr=None, freeze_base_net=False, freeze_net=False, gamma=0.1, lr=0.01, mb2_width_mult=1.0, milestones='80,100', momentum=0.9, net='mb1-ssd', num_epochs=30, num_workers=2, pretrained_ssd='models/mobilenet-v1-ssd-mp-0_675.pth', resume=None, scheduler='cosine', t_max=100, use_cuda=True, validation_epochs=1, weight_decay=0.0005)
2022-03-16 01:54:01 - Prepare training datasets.
warning - could not find image 20220309_123011 - ignoring from dataset
warning - could not find image 20220309_123210 - ignoring from dataset
warning - could not find image 20220309_123213 - ignoring from dataset
warning - could not find image 20220309_123218 - ignoring from dataset
warning - could not find image 20220309_123223 - ignoring from dataset
warning - could not find image 20220309_123224 - ignoring from dataset
warning - could not find image 20220309_123230 - ignoring from dataset
warning - could not find image 20220309_123232 - ignoring from dataset
warning - could not find image 20220309_123233 - ignoring from dataset
warning - could not find image 20220309_123242 - ignoring from dataset
warning - could not find image 20220309_123243 - ignoring from dataset
warning - could not find image 20220309_123303 - ignoring from dataset
warning - could not find image 20220309_123304 - ignoring from dataset
warning - could not find image 20220309_123324 - ignoring from dataset
warning - could not find image 20220309_123325 - ignoring from dataset
warning - could not find image 20220309_123331 - ignoring from dataset
warning - could not find image 20220309_123333 - ignoring from dataset
warning - could not find image 20220309_123334 - ignoring from dataset
warning - could not find image 20220309_123340 - ignoring from dataset
warning - could not find image 20220309_123341 - ignoring from dataset
warning - could not find image 20220309_123349 - ignoring from dataset
warning - could not find image 20220309_123350 - ignoring from dataset
warning - could not find image 20220309_123351 - ignoring from dataset
warning - could not find image 20220309_123400 - ignoring from dataset
warning - could not find image 20220309_123406 - ignoring from dataset
warning - could not find image 20220309_123407 - ignoring from dataset
warning - could not find image 20220309_123416 - ignoring from dataset
warning - could not find image 20220309_123422 - ignoring from dataset
warning - could not find image 20220309_123423 - ignoring from dataset
warning - could not find image 20220309_123430 - ignoring from dataset
warning - could not find image 20220309_123431 - ignoring from dataset
warning - could not find image 20220309_123437 - ignoring from dataset
warning - could not find image 20220309_123438 - ignoring from dataset
warning - could not find image 20220309_123439 - ignoring from dataset
warning - could not find image 20220309_123449 - ignoring from dataset
warning - could not find image 20220309_123450 - ignoring from dataset
warning - could not find image 20220309_123456 - ignoring from dataset
warning - could not find image 20220309_123457 - ignoring from dataset
warning - could not find image 20220309_123506 - ignoring from dataset
warning - could not find image 20220309_123507 - ignoring from dataset
warning - could not find image 20220309_123512 - ignoring from dataset
warning - could not find image 20220309_123513 - ignoring from dataset
warning - could not find image 20220309_123514 - ignoring from dataset
warning - could not find image 20220309_123521 - ignoring from dataset
warning - could not find image 20220309_123522 - ignoring from dataset
warning - could not find image 20220309_123523 - ignoring from dataset
warning - could not find image 20220309_123539 - ignoring from dataset
warning - could not find image 20220309_123540 - ignoring from dataset
warning - could not find image 20220309_123548(0) - ignoring from dataset
warning - could not find image 20220309_123550 - ignoring from dataset
warning - could not find image 20220309_123558 - ignoring from dataset
warning - could not find image 20220309_123559 - ignoring from dataset
warning - could not find image 20220309_123601 - ignoring from dataset
warning - could not find image 20220309_123622 - ignoring from dataset
warning - could not find image 20220309_123623 - ignoring from dataset
warning - could not find image 20220309_123629 - ignoring from dataset
2022-03-16 01:54:01 - VOC Labels read from file: ('BACKGROUND', 'sano', 'epitrix')
2022-03-16 01:54:01 - Stored labels into file models/Dataset/labels.txt.
2022-03-16 01:54:01 - Train dataset size: 0
Traceback (most recent call last):
  File "train_ssd.py", line 237, in <module>
    shuffle=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 224, in __init__
    sampler = RandomSampler(dataset, generator=generator)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/sampler.py", line 96, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
Idk what to do, i compare the .xml file that the tool create, are the same format.
The folders structure is the same, help :(

**Comment by julian998-dot** [comment]
@dusty-nv 
Yep, I found the problem, the folder was named JPG, not JPEG, thank u!
