### ISSUE TITLE
import torchvision error

### ISSUE THREAD

**Issue by namaws** [dusty-nv/jetson-inference#1453]
Hello, I tried to use jetson-inference, but after finishing installation, I tested if pytorch was installed successfully directly in terminal. when doing import torchvision, it showed error below.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.7.0a0-py3.6-linux-aarch64.egg/torchvision/__init__.py", line 6, in <module>
    from torchvision import datasets
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.7.0a0-py3.6-linux-aarch64.egg/torchvision/datasets/__init__.py", line 1, in <module>
    from .lsun import LSUN, LSUNClass
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.7.0a0-py3.6-linux-aarch64.egg/torchvision/datasets/lsun.py", line 2, in <module>
    from PIL import Image
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "/usr/local/lib/python3.6/dist-packages/Pillow-9.2.0-py3.6-linux-aarch64.egg/PIL/Image.py", line 52, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1131, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1112, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 441, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 544, in spec_from_file_location
  File "/usr/local/lib/python3.6/dist-packages/Pillow-9.2.0-py3.6-linux-aarch64.egg/PIL/_deprecate.py", line 1
SyntaxError: future feature annotations is not defined

**Comment by namaws** [comment]
Hello @dusty-nv,
It works! Thank you so much!
