### ISSUE TITLE
Errors Message Received when Training on a custom dataset

### ISSUE THREAD

**Issue by ziyancheng** [dusty-nv/jetson-inference#1549]
@dusty-nv 

I am learning Jetson Fundamentals S3ES on a custom dataset. There is a lot of jpg files when I clicked the button of Capture. However I still got the message as bellows.

**Here is the command I issued:**
```
root@jetson-desktop:/jetson-inference/python/training/classification# python3 train.py --model-dir=models/tools/ --batch-size=4 --workers=1 --epochs=1 data/tools
Use GPU: 0 for training
=> dataset classes:  2 ['background', 'cup']
Traceback (most recent call last):
  File "train.py", line 506, in <module>
    main()

```

**Here is the jpg files** 
```
jetson@jetson-desktop:~/jetson-inference/python/training/classification/data/tools/train/background$ ls -ltr
total 2112
-rw-r--r-- 1 root root 268038 Jan 21 06:45 20230121-114536.jpg
-rw-r--r-- 1 root root 267067 Jan 21 06:45 20230121-114538.jpg
-rw-r--r-- 1 root root 268249 Jan 21 06:45 20230121-114539.jpg
-rw-r--r-- 1 root root 268111 Jan 21 06:45 20230121-114540.jpg
-rw-r--r-- 1 root root 267709 Jan 21 06:45 20230121-114541.jpg
-rw-r--r-- 1 root root 268178 Jan 21 06:45 20230121-114551.jpg
-rw-r--r-- 1 root root 267547 Jan 21 06:45 20230121-114552.jpg
-rw-r--r-- 1 root root 268143 Jan 21 06:45 20230121-114554.jpg

```
**Here is the error messages I received:**
```
Traceback (most recent call last):
  File "train.py", line 506, in <module>
    main()
  File "train.py", line 135, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 191, in main_worker
    normalize,
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.11.0a0+fa347eb-py3.6-linux-aarch64.egg/torchvision/datasets/folder.py", line 313, in __init__
    is_valid_file=is_valid_file)
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.11.0a0+fa347eb-py3.6-linux-aarch64.egg/torchvision/datasets/folder.py", line 146, in __init__
    samples = self.make_dataset(self.root, class_to_idx, extensions, is_valid_file)
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.11.0a0+fa347eb-py3.6-linux-aarch64.egg/torchvision/datasets/folder.py", line 192, in make_dataset
    return make_dataset(directory, class_to_idx, extensions=extensions, is_valid_file=is_valid_file)
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.11.0a0+fa347eb-py3.6-linux-aarch64.egg/torchvision/datasets/folder.py", line 102, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes background, cup. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp

```
Could you please why I received the error messages? Please advise what I missed.

Thanks
Ziyan

**Comment by dusty-nv** [comment]
Hi @ziyancheng, do you also have jpg files under the `val` and `test` subdirectories of your dataset also?  If not, please copy them from `train` and see if that allows it to run.
