### ISSUE TITLE
What are the correct arguments for onnx_export.py if my train_ssd.py resolution=600x600?

### ISSUE THREAD

**Issue by gd08xxx** [dusty-nv/jetson-inference#1572]
Hi @dusty-nv,

Below are my train_ssd.py arguments
```
!python3 train_ssd.py --dataset-type=voc --data=data/final --model-dir=models/final --batch-size=128 --workers=12 --epochs=50 --resolution=600
```
What are the correct arguments required for onnx_export.py? From my source code inspection, seems that width, height and batch-size are the key arguments
```
parser.add_argument('--width', type=int, default=300, help="input width of the model to be exported (in pixels)")
parser.add_argument('--height', type=int, default=300, help="input height of the model to be exported (in pixels)")
parser.add_argument('--batch-size', type=int, default=1, help="batch size of the model to be exported (default=1)")
```
and I expected the below code works
```
python3 onnx_export.py models=models/final --width=600 --height=600 --batch-size=128
```
but after running the code I found out that I received the following error:
```
Namespace(batch_size=128, height=600, input='', labels='labels.txt', model_dir='models/final', net='ssd-mobilenet', output='', width=600)
=> running on device cuda:0
=> found best checkpoint with loss 2.8281142711639404 (models/final/mb1-ssd-Epoch-46-Loss-2.8281142711639404.pth)
creating network:  ssd-mobilenet
num classes:       9
=> loading checkpoint:  models/final/mb1-ssd-Epoch-46-Loss-2.8281142711639404.pth
=> exporting model to ONNX...
/content/pytorch-ssd/vision/ssd/ssd.py:45: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if get_feature_map_size:
/content/pytorch-ssd/vision/ssd/ssd.py:75: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if get_feature_map_size:
/content/pytorch-ssd/vision/ssd/ssd.py:87: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if get_feature_map_size:
/content/pytorch-ssd/vision/ssd/ssd.py:93: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if get_feature_map_size:
Traceback (most recent call last):
  File "onnx_export.py", line 109, in <module>
    torch.onnx.export(net, dummy_input, args.output, verbose=True, input_names=input_names, output_names=output_names)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 504, in export
    _export(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1529, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 1111, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 987, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/usr/local/lib/python3.8/dist-packages/torch/onnx/utils.py", line 891, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 1184, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/usr/local/lib/python3.8/dist-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1182, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/content/pytorch-ssd/vision/ssd/ssd.py", line 101, in forward
    boxes = box_utils.convert_locations_to_boxes(
  File "/content/pytorch-ssd/vision/utils/box_utils.py", line 104, in convert_locations_to_boxes
    locations[..., :2] * center_variance * priors[..., 2:] + priors[..., :2],
RuntimeError: The size of tensor a (11658) must match the size of tensor b (3000) at non-singleton dimension 1
```

Question:
1) Does the batch-size in train_ssd.py related to onnx_export.py's batch-size?

**Comment by gd08xxx** [comment]
***Update***
I checked out the res-512 branch for pytorch-ssd it worked
```
!python3 train_ssd.py --dataset-type=voc --data=data/final --model-dir=models/final --batch-size=128 --workers=12 --epochs=50
!python3 onnx_export.py --model-dir=models/final --batch-size=128
```

**Comment by gd08xxx** [comment]
@dusty-nv may I know whether this is a bug or not?
