### ISSUE TITLE
problem jetson nano 2 gb or 4 gb can not allocate memory

### ISSUE THREAD

**Issue by LeoVerheyden** [dusty-nv/jetson-inference#1601]
Hi . Sorry for my english and I am a newbe
Here the code (error) by following the tuto dusty S1E3.
3 times that a restart all over , I allocated 3.9 swap memory. etc... 
Can you help me ? Thanks

root@mfc-desktop:/jetson-inference/python/training/classification# python3 train.py --model-dir=models/cat_dog --batch-size=4 --workers=1 --epochs=1 data/cat_dog

Epoch: [0] completed, elapsed time 745.963 seconds
Traceback (most recent call last):
  File "train.py", line 458, in <module>
    main(args)
  File "train.py", line 221, in main
    val_loss, val_acc = validate(val_loader, model, criterion, epoch)
  File "train.py", line 323, in validate
    for i, (images, target) in enumerate(val_loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.6/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by dusty-nv** [comment]
Hi @LeoVerheyden, sorry for the delay - I would use `--batch-size=1 --workers=1` and try disabling the desktop GUI if you need to:   https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-transfer-learning.md#disabling-the-desktop-gui
