### ISSUE TITLE
ImportError: jetson_utils_python.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Grissanapong27** [dusty-nv/jetson-inference#1602]
i try to run poseNet.py with python3 on my jetson nano and then 
Traceback (most recent call last):
  File "posenet.py", line 27, in <module>
    from jetson_inference import poseNet
  File "/usr/lib/python3.8/dist-packages/jetson_inference/__init__.py", line 8, in <module>
    from jetson_inference_python import *
ImportError: jetson_utils_python.so: cannot open shared object file: No such file or directory

**Comment by Grissanapong27** [comment]
Yes, I have already done sudo make install and sudo ldconfig and checked in /usr/lib/python3.8/dist-packages. There is already 'jetson/inference' in it. I am able to run docker.
