### ISSUE TITLE
how to use --resume=<CHECKPOINT> argument?

### ISSUE THREAD

**Issue by ugmqu** [dusty-nv/jetson-inference#1662]
The instructions on this [page](https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-ssd.md) are a bit unclear.

How do I resume checkpoint after aborting the training.

just using --resume=CHECKPOINT doesn't work.

Replacing CHECKPOINT with the name of one of the pth doesn't work either

**Comment by ugmqu** [comment]
using
`python3 train_ssd.py --data=data/lego --model-dir=models/lego --batch-size=4 --epochs=30 --resume=mb1-ssd-Epoch-7-Loss-7.6544482707977295.pth`
I get
`Traceback (most recent call last):
  File "train_ssd.py", line 12, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
`

**Comment by dusty-nv** [comment]
> Traceback (most recent call last): File "train_ssd.py", line 12, in <module> import torch ModuleNotFoundError: No module named 'torch'

@ugmqu do you only get this import error when using `--resume` ?    Do you have PyTorch installed?    Can you run `python3 -c 'import torch; print(torch.__version__)'`

**Comment by ugmqu** [comment]
reflashed the jetson nano. It works now

**Comment by 4boris** [comment]
How do you find the name of the checkpoint path?

**Comment by exploremore691** [comment]
I got the same issue 
using
python3 train_ssd.py --data=data/lego --model-dir=models/lego --batch-size=4 --epochs=30 --resume=mb1-ssd-Epoch-7-Loss-7.6544482707977295.pth
I get
Traceback (most recent call last): File "train_ssd.py", line 12, in <module> import torch ModuleNotFoundError: No module named 'torch' 
 
and then to fix it but 

/Downloads/jetson-inference/python/training/detection/ssd$ python3 train_ssd.py --dataset-type=voc --data=data/img --model-dir=models/img
Traceback (most recent call last):
  File "train_ssd.py", line 20, in <module>
    from vision.ssd.vgg_ssd import create_vgg_ssd
  File "/home/me/Downloads/jetson-inference/python/training/detection/ssd/vision/ssd/vgg_ssd.py", line 6, in <module>
    from .predictor import Predictor
  File "/home/me/Downloads/jetson-inference/python/training/detection/ssd/vision/ssd/predictor.py", line 4, in <module>
    from .data_preprocessing import PredictionTransform
  File "/home/me/Downloads/jetson-inference/python/training/detection/ssd/vision/ssd/data_preprocessing.py", line 1, in <module>
    from ..transforms.transforms import *
  File "/home/me/Downloads/jetson-inference/python/training/detection/ssd/vision/transforms/transforms.py", line 5, in <module>
    from torchvision import transforms
ModuleNotFoundError: No module named 'torchvision'
