### ISSUE TITLE
Unable to run author's TAO converter with resnet18_facedetect_pruned.etlt

### ISSUE THREAD

**Issue by hardrad** [dusty-nv/jetson-inference#1792]
Example "detectnet.py --model=facedetect "images/humans_*.jpg" images/test/facedetect_humans_%i.jpg" doesnt work. In this case, I tried to run tao-converter that downloaded together with *.etlt model, colors.txt and int8_calibration,txt with labels.txt. 
Than, i ran ./tao-converter ant got a error message "error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory."

Could anyone help with this issue? It is very annoying, because I tried to run an example model, not even my own TAO-models.

**Comment by hardrad** [comment]
Hi! First of all, I would like to express my admiration for your jetson-inference support here and via nvidia forum. It is one the deepest support by project's author i ever seen!

Yesterday, right after I opened the thread, I saw that this was an issue with jetpack 6, However, thank you for your fast answer!
Can i make etlt-TRT conversion by myself without reflashing my Jetson Orin Nano to previous version?

**Comment by hardrad** [comment]
I solved the problem. I donwloaded actual tao-converter from Nvidia resourses. 
And the next strange steps:
1) Call your model with .sh tao-donwloader with your model name. My model is facedetect 2.0.1 pruned
2) You will receive the error message about libcrypto after model download. 
3) Inside .sh tao model downloader  comment string with "download_tao_converter" function
4) Put actual tao-converter in folder. Run chmod +x for tao-converter for give permission
5) Go back to previous folder and run tao-downloader .sh the next time. Why so strange approach?
I got some issues with keys for ./tao-converter call. Thus, it is simpler to run automatic keys demarkation inside dusty-nv's .sh file, than wasting time for key's syntaxis understanding. 

I succesfully ran model via jetson-inference

**Comment by dusty-nv** [comment]
Thanks @hardrad!   Which tao-converter did you download that worked for you on JetPack 6?   I can add it to the jetson-inference scripts so that it works for everyone.

**Comment by hardrad** [comment]
I dowloaded v5.1.0_jp6.0_aarch64 (SUDDENLY!) tao-converter from NGC Catalog (need regitstration)

**Comment by Embosen** [comment]
hi @dusty-nv ,I encountered the same issue in the latest R36.3.0 version of the docker container, is it still not resolved?

**Comment by Embosen** [comment]
I solved the problem,thanks

**Comment by AkshatJain-TerraFirma** [comment]
Hello @dusty-nv , I am encountering a similar issue but while trying to run object detection using the peoplenet model, I am on JetPack6. SSD-mobilenet-v2 works perfectly but other models don't. 

**Below are the logs :** 

akshat@person-detector:~/terrafirma/v2$ /bin/python /home/akshat/terrafirma/v2/operator_station/vehicle_control/detect.py
jetson.inference -- detectNet loading custom model '(null)'
[TRT]    running model command:  tao-model-downloader.sh peoplenet_deployable_quantized_v2.6.1
ARCH:  aarch64
reading L4T version from /etc/nv_tegra_release
L4T BSP Version:  L4T R36.3.0
[TRT]    downloading peoplenet_deployable_quantized_v2.6.1
resnet34_peoplenet_int8.etlt         100%[======================================================================>]  85.02M  11.6MB/s    in 8.7s    
resnet34_peoplenet_int8.txt          100%[======================================================================>]   9.20K  --.-KB/s    in 0.002s  
labels.txt                           100%[======================================================================>]      17  --.-KB/s    in 0s      
colors.txt                           100%[======================================================================>]      27  --.-KB/s    in 0s      
[TRT]    downloading tao-converter from https://api.ngc.nvidia.com/v2/resources/nvidia/tao/tao-converter/versions/v3.22.05_trt8.4_aarch64/files/tao-converter
tao-converter                        100%[======================================================================>] 128.62K  --.-KB/s    in 0.06s   
detectNet -- converting TAO model to TensorRT engine:
          -- input          resnet34_peoplenet_int8.etlt
          -- output         resnet34_peoplenet_int8.etlt.engine
          -- calibration    resnet34_peoplenet_int8.txt
          -- encryption_key tlt_encode
          -- input_dims     3,544,960
          -- output_layers  output_bbox/BiasAdd,output_cov/Sigmoid
          -- max_batch_size 1
          -- workspace_size 4294967296
          -- precision      int8
./tao-converter: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
[TRT]    failed to convert model 'resnet34_peoplenet_int8.etlt' to TensorRT...
[TRT]    failed to download model after 2 retries
[TRT]    if this error keeps occuring, see here for a mirror to download the models from:
[TRT]       https://github.com/dusty-nv/jetson-inference/releases
[TRT]    failed to download built-in detection model 'peoplenet'
Traceback (most recent call last):
  File "/home/akshat/terrafirma/v2/operator_station/vehicle_control/detect.py", line 8, in <module>
    net = jetson_inference.detectNet("peoplenet", threshold=0.5)
Exception: jetson.inference -- detectNet failed to load network


**When i re-run the same script this is the log :**


akshat@person-detector:~/terrafirma/v2$ /bin/python /home/akshat/terrafirma/v2/operator_station/vehicle_control/detect.py
jetson.inference -- detectNet loading custom model '(null)'

detectNet -- loading detection network model from:
          -- prototxt     
          -- model        networks/peoplenet_deployable_quantized_v2.6.1/resnet34_peoplenet_int8.etlt.engine
          -- input_blob   'input_1'
          -- output_cvg   'output_cov/Sigmoid'
          -- output_bbox  'output_bbox/BiasAdd'
          -- mean_pixel   0.000000
          -- class_labels networks/peoplenet_deployable_quantized_v2.6.1/labels.txt
          -- class_colors networks/peoplenet_deployable_quantized_v2.6.1/colors.txt
          -- threshold    0.500000
          -- batch_size   1

[TRT]    TensorRT version 8.6.2
[TRT]    loading NVIDIA plugins...
[TRT]    Registered plugin creator - ::BatchedNMSDynamic_TRT version 1
[TRT]    Registered plugin creator - ::BatchedNMS_TRT version 1
[TRT]    Registered plugin creator - ::BatchTilePlugin_TRT version 1
[TRT]    Registered plugin creator - ::Clip_TRT version 1
[TRT]    Registered plugin creator - ::CoordConvAC version 1
[TRT]    Registered plugin creator - ::CropAndResizeDynamic version 1
[TRT]    Registered plugin creator - ::CropAndResize version 1
[TRT]    Registered plugin creator - ::DecodeBbox3DPlugin version 1
[TRT]    Registered plugin creator - ::DetectionLayer_TRT version 1
[TRT]    Registered plugin creator - ::EfficientNMS_Explicit_TF_TRT version 1
[TRT]    Registered plugin creator - ::EfficientNMS_Implicit_TF_TRT version 1
[TRT]    Registered plugin creator - ::EfficientNMS_ONNX_TRT version 1
[TRT]    Registered plugin creator - ::EfficientNMS_TRT version 1
[TRT]    Could not register plugin creator -  ::FlattenConcat_TRT version 1
[TRT]    Registered plugin creator - ::GenerateDetection_TRT version 1
[TRT]    Registered plugin creator - ::GridAnchor_TRT version 1
[TRT]    Registered plugin creator - ::GridAnchorRect_TRT version 1
[TRT]    Registered plugin creator - ::InstanceNormalization_TRT version 1
[TRT]    Registered plugin creator - ::InstanceNormalization_TRT version 2
[TRT]    Registered plugin creator - ::LReLU_TRT version 1
[TRT]    Registered plugin creator - ::ModulatedDeformConv2d version 1
[TRT]    Registered plugin creator - ::MultilevelCropAndResize_TRT version 1
[TRT]    Registered plugin creator - ::MultilevelProposeROI_TRT version 1
[TRT]    Registered plugin creator - ::MultiscaleDeformableAttnPlugin_TRT version 1
[TRT]    Registered plugin creator - ::NMSDynamic_TRT version 1
[TRT]    Registered plugin creator - ::NMS_TRT version 1
[TRT]    Registered plugin creator - ::Normalize_TRT version 1
[TRT]    Registered plugin creator - ::PillarScatterPlugin version 1
[TRT]    Registered plugin creator - ::PriorBox_TRT version 1
[TRT]    Registered plugin creator - ::ProposalDynamic version 1
[TRT]    Registered plugin creator - ::ProposalLayer_TRT version 1
[TRT]    Registered plugin creator - ::Proposal version 1
[TRT]    Registered plugin creator - ::PyramidROIAlign_TRT version 1
[TRT]    Registered plugin creator - ::Region_TRT version 1
[TRT]    Registered plugin creator - ::Reorg_TRT version 1
[TRT]    Registered plugin creator - ::ResizeNearest_TRT version 1
[TRT]    Registered plugin creator - ::ROIAlign_TRT version 1
[TRT]    Registered plugin creator - ::RPROI_TRT version 1
[TRT]    Registered plugin creator - ::ScatterND version 1
[TRT]    Registered plugin creator - ::SpecialSlice_TRT version 1
[TRT]    Registered plugin creator - ::Split version 1
[TRT]    Registered plugin creator - ::VoxelGeneratorPlugin version 1
[TRT]    completed loading NVIDIA plugins.
[TRT]    detected model format - engine  (extension '.engine')
[TRT]    loading network plan from engine cache... 
[TRT]    failed to load engine cache from 
[TRT]    failed to load 
[TRT]    detectNet -- failed to initialize.
Traceback (most recent call last):
  File "/home/akshat/terrafirma/v2/operator_station/vehicle_control/detect.py", line 8, in <module>
    net = jetson_inference.detectNet("peoplenet", threshold=0.5)
Exception: jetson.inference -- detectNet failed to load network


** Part of The Python script I am using"
import jetson_inference
import jetson_utils
from control_cmds import send_command_by_key
# Initialize the detectNet model
net = jetson_inference.detectNet("peoplenet", threshold=0.5)

**Comment by alex-bizkrovnyi** [comment]
> v5.1.0_jp6.0_aarch64
Put actual link for download

https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/resources/tao-converter/files?version=v5.1.0_jp6.0_aarch64

**Comment by alex-bizkrovnyi** [comment]
I would like to add more info based on @hardrad response.

1. Remove your downloaded before model from `jetson-inference/build/aarch64/bin/networks`
1. Go to your **jetson-inference** installation folder and then go to **tools** folder
2. Open` tao-model-downloader.sh` with **Vim** and _remove/comment_ in `function tao_to_trt()` the **download_tao_converter** method invocation.
3. Go to https://catalog.ngc.nvidia.com/orgs/nvidia/teams/tao/resources/tao-converter/files?version=v5.1.0_jp6.0_aarch64 and click **exactly** on the file, **NOT Download button**.
![image](https://github.com/user-attachments/assets/adb4ff46-bfe6-4b39-9747-82feeb2a5f5c)
4. Once you downloaded **tao-converter**, go to the **jetson-inference/tools** folder and run `./tao-model-downloader.sh <your_model_name>`. The model name can be found here 
```
#
# command-line parsing
#
MODEL="$1"

echo "$LOG downloading $MODEL"

if [[ "$MODEL" == "peoplenet_deployable_quantized_v2.6.1" ]]; then
        download_peoplenet_v261
elif [[ "$MODEL" == "peoplenet_pruned_quantized_v2.3.2" ]]; then
        download_peoplenet_v232
elif [[ "$MODEL" == "dashcamnet_pruned_v1.0.3" ]]; then
        download_dashcamnet_v103
elif [[ "$MODEL" == "trafficcamnet_pruned_v1.0.3" ]]; then
        download_trafficcamnet_v103
elif [[ "$MODEL" == "facedetect_pruned_quantized_v2.0.1" ]]; then
        download_facedetect_v201
else
        echo "$LOG error -- invalid or unknown model selected ($MODEL)"
        exit 1
fi

exit 0
```
5. After model is downloaded, script will try to convert model using **tao-converter**, which was not downloaded, due to your commenting/deleting this method invocation and this model downloading process will be finished with error.
6. Copy downloaded v5.1.0_jp6.0_aarch64 **tao-converter** into `jetson-inference/build/aarch64/bin/networks/<your model_name>/`.
7. run there `chmod +x tao-converter`
8. Go to **jetson-inference/tools** folder and run` ./tao-model-downloader.sh <your_model_name>`. This time it will not download **tao-converter**, because you commented this command and once models are downloaded, the correct **tao-converter** will be invoked, because you already moved it into `jetson-inference/build/aarch64/bin/networks/<your model_name>/`
9. Downloading process finished with success.

**Comment by stephen-derosa** [comment]
I am also hitting the issues mentioned in this thread on an ORIN AGX running jetpack 6.2 on the host inside of jetson-inference `dustynv/jetson-inference:r36.3.0` container. While downloading the `tao_downloader` from `ngc` does resolve the `libcrypto` issue, i am unable to successfully convert any models. For example, for peoplenet i get the error:
```
[INFO] [MemUsageChange] Init CUDA: CPU +12, GPU +0, now: CPU 33, GPU 11118 (MiB)
[INFO] [MemUsageChange] Init builder kernel library: CPU +1154, GPU +1421, now: CPU 1223, GPU 12579 (MiB)
[WARNING] The implicit batch dimension mode has been deprecated. Please create the network with NetworkDefinitionCreationFlag::kEXPLICIT_BATCH flag whenever possible.
[INFO] Graph optimization time: 0.00429106 seconds.
[INFO] Reading Calibration Cache for calibrator: EntropyCalibration2
[INFO] Generated calibration scales using calibration cache. Make sure that calibration cache has latest scales.
[INFO] To regenerate calibration cache, please delete the existing one. TensorRT will generate a new calibration cache.
[WARNING] Missing scale and zero-point for tensor output_bbox/bias, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor conv1/kernel, expect fall back to non-int8 implementation for any layer consuming or producing given tensor

...
[WARNING] Missing scale and zero-point for tensor output_cov/kernel, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[WARNING] Missing scale and zero-point for tensor output_cov/bias, expect fall back to non-int8 implementation for any layer consuming or producing given tensor
[INFO] Graph optimization time: 0.0458754 seconds.
[INFO] Local timing cache in use. Profiling results in this builder pass will not be stored.
[INFO] Detected 1 inputs and 2 output network tensors.
[INFO] Total Host Persistent Memory: 249744
[INFO] Total Device Persistent Memory: 0
[INFO] Total Scratch Memory: 0
[INFO] [MemUsageStats] Peak memory usage of TRT CPU/GPU memory allocators: CPU 10 MiB, GPU 35 MiB
[INFO] [BlockAssignment] Started assigning block shifts. This will take 51 steps to complete.
[INFO] [BlockAssignment] Algorithm ShiftNTopDown took 0.827297ms to assign 4 blocks to 51 nodes requiring 8551936 bytes.
[INFO] Total Activation Memory: 8551936
[INFO] (Sparsity) Layers eligible for sparse math:
[INFO] (Sparsity) TRT inference plan picked sparse implementation for layers:
[WARNING] TensorRT encountered issues when converting weights between types and that could affect accuracy.
[WARNING] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
[WARNING] Check verbose logs for the list of affected weights.
[WARNING] - 49 weights are affected by this issue: Detected subnormal FP16 values.
[WARNING] - 26 weights are affected by this issue: Detected values less than smallest positive FP16 subnormal value and converted them to the FP16 minimum subnormalized value.
[INFO] [MemUsageChange] TensorRT-managed allocation in building engine: CPU +2, GPU +4, now: CPU 2, GPU 4 (MiB)
double free or corruption (out)
./tao-model-downloader.sh: line 164: 16107 Aborted                 (core dumped) ./tao-converter -k $encryption_key -d $input_dims -o $output_layers -m $max_batch_size -w $workspace_size -t $precision -c $calibration -e $model_output $model_input
[TRT]    failed to convert model 'resnet34_peoplenet_pruned_int8.etlt' to TensorRT...
```

Any help is appreciated! Thanks in advance!
