### ISSUE TITLE
Error installing Digits on Host

### ISSUE THREAD

**Issue by gustavz** [dusty-nv/jetson-inference#181]
When i try to Install DIGITS on my Host Laptop (Ubuntu 16.04)
and i run this command:
`$ sudo pip install -r requirements.txt`
it gives me this output after some successfull Package Downloads:

```
Collecting pydot<=1.0.29,>=1.0.28 (from -r requirements.txt (line 16))
  Downloading pydot-1.0.29.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-lkybulx2/pydot/setup.py", line 6, in <module>
        import pydot
      File "/tmp/pip-build-lkybulx2/pydot/pydot.py", line 31
        except Exception, e:
                        ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lkybulx2/pydot/
```
 

Any Hints/Help or similar Experiences?

**Comment by AsternA** [comment]
Same issue.
Ubuntu 16.04
