### ISSUE TITLE
Support for "Square" op in tensorflow to UFF parser conversion for TensorRT

### ISSUE THREAD

**Issue by achbogga** [dusty-nv/jetson-inference#219]
Hello Dusty,

I am trying to convert the famous [Facenet Face Recognition](https://github.com/davidsandberg/facenet) tensorflow pretrained model to tensorRT engine. 

I don't have the option to retrain the model. Please find the UFF parser log below while trying to do this.
Converting to UFF graph
Warning: keep_dims is not supported, ignoring...
Warning: No conversion function registered for layer: Square yet.
Converting as custom op Square embeddings/Square
name: "embeddings/Square"
op: "Square"
input: "InceptionResnetV1/Bottleneck/BatchNorm/batchnorm/add_1"
attr {
  key: "T"
  value {
    type: DT_FLOAT
  }
}

Traceback (most recent call last):
  File "Desktop/facenet_graph.py", line 29, in <module>
    uff_model = uff.from_tensorflow(tf_model, ["embeddings"])
  File "/home/ovuser/tensorflow/local/lib/python2.7/site-packages/uff/converters/tensorflow/conversion_helpers.py", line 75, in from_tensorflow
    name="main")
  File "/home/ovuser/tensorflow/local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 64, in convert_tf2uff_graph
    uff_graph, input_replacements)
  File "/home/ovuser/tensorflow/local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 51, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes)
  File "/home/ovuser/tensorflow/local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 28, in convert_layer
    fields = cls.parse_tf_attrs(tf_node.attr)
  File "/home/ovuser/tensorflow/local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 177, in parse_tf_attrs
    for key, val in attrs.items()}
  File "/home/ovuser/tensorflow/local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 177, in <dictcomp>
    for key, val in attrs.items()}
  File "/home/ovuser/tensorflow/local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 172, in parse_tf_attr_value
    return cls.convert_tf2uff_field(code, val)
  File "/home/ovuser/tensorflow/local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 146, in convert_tf2uff_field
    return TensorFlowToUFFConverter.convert_tf2numpy_dtype(val)
  File "/home/ovuser/tensorflow/local/lib/python2.7/site-packages/uff/converters/tensorflow/converter.py", line 74, in convert_tf2numpy_dtype
    return np.dtype(dt[dtype])
TypeError: list indices must be integers, not AttrValue

I have followed the developer guide and executed all the steps necessary. Please let me know how to add the support for that particular operation so that I can do it myself if possible. Or else, please raise a ticket at your end and make this happen. I really appreciate your effort and time.

**Comment by dusty-nv** [comment]
Hi achbogga, this repo uses caffemodel + TensorRT, please post your issue to the Jetson forums if you haven't already:  https://devtalk.nvidia.com/default/board/139/jetson-embedded-systems/
