### ISSUE TITLE
Segmentation fault in nvinfer1::cudnn::deserializeDims when using custom alexnet model

### ISSUE THREAD

**Issue by VivekMaran27** [dusty-nv/jetson-inference#257]
Platform:
Jetson-TX2

Versions:
sudo dpkg -l | grep TensorRT
ii  libnvinfer-dev                                           4.0.4-1+cuda9.0                               arm64        TensorRT development libraries and headers
ii  libnvinfer-samples                                       4.0.4-1+cuda9.0                               arm64        TensorRT samples and documentation
ii  libnvinfer4                                              4.0.4-1+cuda9.0                               arm64        TensorRT runtime libraries
ii  tensorrt                                                 3.0.4-1+cuda9.0                               arm64        Meta package of TensorRT

**Backtrace:**
#0  0x0000007fb0d14c1c in nvinfer1::cudnn::deserializeDims(ifb::Dims const&) () from /usr/lib/aarch64-linux-gnu/libnvinfer.so.4
#1  0x0000007fb0c9eb94 in nvinfer1::cudnn::Engine::deserialize(void const*, unsigned long, nvinfer1::IPluginFactory*) ()
#2  0x0000007fb0c98010 in nvinfer1::Runtime::deserializeCudaEngine(void const*, unsigned long, nvinfer1::IPluginFactory*) ()
#3  0x0000007fb7eb2250 in tensorNet::LoadNetwork(char const*, char const*, char const*, char const*, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, unsigned int) ()
#4  0x0000007fb7eb1d2c in tensorNet::LoadNetwork(char const*, char const*, char const*, char const*, char const*, unsigned int) ()
#5  0x0000007fb7eaece4 in imageNet::init(char const*, char const*, char const*, char const*, char const*, char const*, unsigned int)
#6  0x0000007fb7eaea50 in imageNet::Create(char const*, char const*, char const*, char const*, char const*, char const*, unsigned int) () from /home/nvidia/Vivek/repos/occupancy_detection/jetson-inference/build/aarch64/lib/libjetson-inference.so
#7  0x0000007fb7eaf030 in imageNet::Create(int, char**) ()
#8  0x000000000040753c in main ()

**Comment by VivekMaran27** [comment]
It seems that the TensorRT was trying to load the tensorcache file (which was exported from someother system) and causing a crash. Hence i removed the tensorcache file which fixed the issue.
