### ISSUE TITLE
ERROR: error code 1 Object Detection Nvidia Digits training custom model using custom dataset

### ISSUE THREAD

**Issue by spurani** [dusty-nv/jetson-inference#380]
@dusty-nv  Basically I am trying to locate objects using Dectnet with the help of your guide well it gives same error over and over again. I worked with image classification previously it didn't cause any issues. This is the detailed error

Iteration 2124 (1.68974 iter/s, 5.32627s/9 iter), loss = 14.3181
Train net output #0: loss_bbox = 1.77657 (* 2 = 3.55315 loss)
Train net output #1: loss_coverage = 35.0513 (* 1 = 35.0513 loss)
Iteration 2124, lr = 1.89462e-05
Iteration 2133 (1.68658 iter/s, 5.33624s/9 iter), loss = 8.62086
Train net output #0: loss_bbox = 1.21403 (* 2 = 2.42807 loss)
Train net output #1: loss_coverage = 7.49041 (* 1 = 7.49041 loss)
Iteration 2133, lr = 1.89239e-05
Iteration 2142 (1.68812 iter/s, 5.33138s/9 iter), loss = 70.7058
Train net output #0: loss_bbox = 1.93409 (* 2 = 3.86817 loss)
Train net output #1: loss_coverage = 6.00068 (* 1 = 6.00068 loss)
Iteration 2142, lr = 1.89017e-05
Iteration 2151 (1.69077 iter/s, 5.32302s/9 iter), loss = 52.4534
Train net output #0: loss_bbox = 0.888928 (* 2 = 1.77786 loss)
Train net output #1: loss_coverage = 8.80742 (* 1 = 8.80742 loss)
Iteration 2151, lr = 1.88795e-05
Iteration 2156, Testing net (#0)
Ignoring source layer train_data
Ignoring source layer train_label
Ignoring source layer train_transform

**Checked caffe_output.log**
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/om/hd/infra/build_opencv/opencv/modules/core/src/matrix.cpp, line 2034
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/om/hd/infra/build_opencv/opencv/modules/core/src/matrix.cpp, line 2034
Traceback (most recent call last):
File "/home/userprofile/caffe/python/caffe/layers/detectnet/clustering.py", line 133, in forward
bbox = cluster(self, data0, bottom[1].data)
File "/home/userprofile/caffe/python/caffe/layers/detectnet/clustering.py", line 227, in cluster
boxes_cur_image = vote_boxes(propose_boxes, propose_cvgs, mask, self)
File "/home/userprofile/caffe/python/caffe/layers/detectnet/clustering.py", line 193, in vote_boxes
self.gridbox_rect_eps)
cv2.error: /home/om/hd/infra/build_opencv/opencv/modules/core/src/matrix.cpp:2034: error: (-213) Unknown/unsupported array type in function type

I applied Batch size: 1 and Batch accumulation: 4

I tried to look it up on google couldn't find any relevant results which I could follow. Could please take a look? and it would be great if you could guide me through this. thanks and cheers 

![image](https://user-images.githubusercontent.com/28580888/62431836-3becd700-b6f9-11e9-974a-bbb4154df7cc.png)

**Comment by spurani** [comment]
ssue fixed I was having 2 python versions one was 2.7 and second was 3.0 and both the python versions were being called for same file or different file( not sure) and both the python version were having different python-opencv version so whenever a default version of python was called it was expecting any one pyhton-opencv version call while there were 2 so they were clashing. So just make sure you have single python version and single opencv version which is set to default automatically or manually. Doesn't matter if you have 2 python version but there should be one python-opencv version which could be used by both python versions. Also before making any changes just refer your Makefile.config or Makefile.config.example from where actual build directory was generated. After removing pyhton version or pyhton-opencv version you don't need to reinstall everything just continue with your work. But just check both python versions are calling specific/same pyhton-opencv version. or you could check pyhton version is having pyhton-opencv version.
