### ISSUE TITLE
Custom models (PyTorch, ONNX, Caffe)

### ISSUE THREAD

**Issue by theDweeb** [dusty-nv/jetson-inference#479]
Hello, I am currently trying to run custom models on the Nvidia Xavier using this jetson-inference repo. I have gone through the tutorials using the prebuilt networks just fine but when I try to use custom models I run into problems.

### Pretrained MobileNetV2 model from Torchvision

I converted it to ONNX format using [this](https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html)

`Exported model has been tested with ONNXRuntime, and the result looks good!
`

but fails the TensorRT onnx test:
```
/usr/src/tensorrt/bin/trtexec --onnx=onnx_models/MobileNetV2.onnx 
&&&& RUNNING TensorRT.trtexec # /usr/src/tensorrt/bin/trtexec --onnx=onnx_models/MobileNetV2.onnx
[01/17/2020-11:34:07] [I] === Model Options ===
[01/17/2020-11:34:07] [I] Format: ONNX
[01/17/2020-11:34:07] [I] Model: onnx_models/MobileNetV2.onnx
[01/17/2020-11:34:07] [I] Output:
[01/17/2020-11:34:07] [I] === Build Options ===
[01/17/2020-11:34:07] [I] Max batch: 1
[01/17/2020-11:34:07] [I] Workspace: 16 MB
[01/17/2020-11:34:07] [I] minTiming: 1
[01/17/2020-11:34:07] [I] avgTiming: 8
[01/17/2020-11:34:07] [I] Precision: FP32
[01/17/2020-11:34:07] [I] Calibration: 
[01/17/2020-11:34:07] [I] Safe mode: Disabled
[01/17/2020-11:34:07] [I] Save engine: 
[01/17/2020-11:34:07] [I] Load engine: 
[01/17/2020-11:34:07] [I] Inputs format: fp32:CHW
[01/17/2020-11:34:07] [I] Outputs format: fp32:CHW
[01/17/2020-11:34:07] [I] Input build shapes: model
[01/17/2020-11:34:07] [I] === System Options ===
[01/17/2020-11:34:07] [I] Device: 0
[01/17/2020-11:34:07] [I] DLACore: 
[01/17/2020-11:34:07] [I] Plugins:
[01/17/2020-11:34:07] [I] === Inference Options ===
[01/17/2020-11:34:07] [I] Batch: 1
[01/17/2020-11:34:07] [I] Iterations: 10
[01/17/2020-11:34:07] [I] Duration: 3s (+ 200ms warm up)
[01/17/2020-11:34:07] [I] Sleep time: 0ms
[01/17/2020-11:34:07] [I] Streams: 1
[01/17/2020-11:34:07] [I] ExposeDMA: Disabled
[01/17/2020-11:34:07] [I] Spin-wait: Disabled
[01/17/2020-11:34:07] [I] Multithreading: Disabled
[01/17/2020-11:34:07] [I] CUDA Graph: Disabled
[01/17/2020-11:34:07] [I] Skip inference: Disabled
[01/17/2020-11:34:07] [I] Input inference shapes: model
[01/17/2020-11:34:07] [I] Inputs:
[01/17/2020-11:34:07] [I] === Reporting Options ===
[01/17/2020-11:34:07] [I] Verbose: Disabled
[01/17/2020-11:34:07] [I] Averages: 10 inferences
[01/17/2020-11:34:07] [I] Percentile: 99
[01/17/2020-11:34:07] [I] Dump output: Disabled
[01/17/2020-11:34:07] [I] Profile: Disabled
[01/17/2020-11:34:07] [I] Export timing to JSON file: 
[01/17/2020-11:34:07] [I] Export output to JSON file: 
[01/17/2020-11:34:07] [I] Export profile to JSON file: 
[01/17/2020-11:34:07] [I] 
----------------------------------------------------------------
Input filename:   onnx_models/MobileNetV2.onnx
ONNX IR version:  0.0.4
Opset version:    10
Producer name:    pytorch
Producer version: 1.2
Domain:           
Model version:    0
Doc string:       
----------------------------------------------------------------
[01/17/2020-11:34:08] [W] [TRT] Calling isShapeTensor before the entire network is constructed may result in an inaccurate result.
[01/17/2020-11:34:08] [E] [TRT] Network has dynamic or shape inputs, but no optimization profile has been defined.
[01/17/2020-11:34:08] [E] [TRT] Network validation failed.
[01/17/2020-11:34:08] [E] Engine creation failed
[01/17/2020-11:34:08] [E] Engine set up failed
&&&& FAILED TensorRT.trtexec # /usr/src/tensorrt/bin/trtexec --onnx=onnx_models/MobileNetV2.onnx
```

I have tried PyTorch 1.1 (which fails at converting model to ONNX due to dynamic_axes label), PyTorch 1.2 and 1.3

### Pre-trained MobileNetV2 

model found [here](https://github.com/onnx/models/tree/master/vision/classification/mobilenet)

Passes the trtexec:

`&&&& PASSED TensorRT.trtexec # /usr/src/tensorrt/bin/trtexec --onnx=onnx_models/mobilenetv2-1.0.onnx
`

but runs into an error when loading model with jerson-inference:
```
./imagenet-console.py airplane_0.jpg output_0.jpg --model=mobilenetv2-1.0.onnx 
jetson.inference.__init__.py
jetson.inference -- initializing Python 2.7 bindings...
jetson.inference -- registering module types...
jetson.inference -- done registering module types
jetson.inference -- done Python 2.7 binding initialization
jetson.utils.__init__.py
jetson.utils -- initializing Python 2.7 bindings...
jetson.utils -- registering module functions...
jetson.utils -- done registering module functions
jetson.utils -- registering module types...
jetson.utils -- done registering module types
jetson.utils -- done Python 2.7 binding initialization
[image] loaded 'airplane_0.jpg'  (500 x 375, 3 channels)
jetson.inference -- PyTensorNet_New()
jetson.inference -- PyImageNet_Init()
jetson.inference -- imageNet loading network using argv command line params
jetson.inference -- imageNet.__init__() argv[0] = './imagenet-console.py'
jetson.inference -- imageNet.__init__() argv[1] = 'airplane_0.jpg'
jetson.inference -- imageNet.__init__() argv[2] = 'output_0.jpg'
jetson.inference -- imageNet.__init__() argv[3] = '--model=mobilenetv2-1.0.onnx'
[TRT]   imageNet -- failed to initialize.
jetson.inference -- imageNet failed to load built-in network 'googlenet'
PyTensorNet_Dealloc()
Traceback (most recent call last):
  File "./imagenet-console.py", line 49, in <module>
    net = jetson.inference.imageNet(opt.network, sys.argv)
Exception: jetson.inference -- imageNet failed to load network
jetson.utils -- freeing CUDA mapped memory

```

### Pretrained MobileNetV2 Caffe Model
model found [here](https://github.com/zhanghanbin3159/MobileNetV2-SSD)

```
./imagenet-console.py airplane_0.jpg output_0.jpg --prototxt= MobileNet_deploy.prototxt \ 
--model=MobileNetSSD_deploy.caffemodel \ 
--labels=labels_map.txt \
--input_blob=data \
--output_blob=softmax
jetson.inference.__init__.py
jetson.inference -- initializing Python 2.7 bindings...
jetson.inference -- registering module types...
jetson.inference -- done registering module types
jetson.inference -- done Python 2.7 binding initialization
jetson.utils.__init__.py
jetson.utils -- initializing Python 2.7 bindings...
jetson.utils -- registering module functions...
jetson.utils -- done registering module functions
jetson.utils -- registering module types...
jetson.utils -- done registering module types
jetson.utils -- done Python 2.7 binding initialization
[image] loaded 'airplane_0.jpg'  (500 x 375, 3 channels)
jetson.inference -- PyTensorNet_New()
jetson.inference -- PyImageNet_Init()
jetson.inference -- imageNet loading network using argv command line params
jetson.inference -- imageNet.__init__() argv[0] = './imagenet-console.py'
jetson.inference -- imageNet.__init__() argv[1] = 'airplane_0.jpg'
jetson.inference -- imageNet.__init__() argv[2] = 'output_0.jpg'
jetson.inference -- imageNet.__init__() argv[3] = '--prototxt='
jetson.inference -- imageNet.__init__() argv[4] = 'MobileNet_deploy.prototxt'
jetson.inference -- imageNet.__init__() argv[5] = '--model=MobileNetSSD_deploy.caffemodel'
jetson.inference -- imageNet.__init__() argv[6] = '--labels=labels_map.txt'
jetson.inference -- imageNet.__init__() argv[7] = '--input_blob=data'
jetson.inference -- imageNet.__init__() argv[8] = '--output_blob=softmax'

imageNet -- loading classification network model from:
         -- prototxt     
         -- model        MobileNetSSD_deploy.caffemodel
         -- class_labels labels_map.txt
         -- input_blob   'data'
         -- output_blob  'softmax'
         -- batch_size   1

[TRT]   TensorRT version 6.0.1
[TRT]   loading NVIDIA plugins...
[TRT]   Plugin Creator registration succeeded - GridAnchor_TRT
[TRT]   Plugin Creator registration succeeded - GridAnchorRect_TRT
[TRT]   Plugin Creator registration succeeded - NMS_TRT
[TRT]   Plugin Creator registration succeeded - Reorg_TRT
[TRT]   Plugin Creator registration succeeded - Region_TRT
[TRT]   Plugin Creator registration succeeded - Clip_TRT
[TRT]   Plugin Creator registration succeeded - LReLU_TRT
[TRT]   Plugin Creator registration succeeded - PriorBox_TRT
[TRT]   Plugin Creator registration succeeded - Normalize_TRT
[TRT]   Plugin Creator registration succeeded - RPROI_TRT
[TRT]   Plugin Creator registration succeeded - BatchedNMS_TRT
[TRT]   Could not register plugin creator:  FlattenConcat_TRT in namespace: 
[TRT]   completed loading NVIDIA plugins.
[TRT]   detected model format - caffe  (extension '.caffemodel')
[TRT]   desired precision specified for GPU: FASTEST
[TRT]   requested fasted precision for device GPU without providing valid calibrator, disabling INT8
[TRT]   native precisions detected for GPU:  FP32, FP16, INT8
[TRT]   selecting fastest native precision for GPU:  FP16
[TRT]   attempting to open engine cache file MobileNetSSD_deploy.caffemodel.1.1.GPU.FP16.engine
[TRT]   cache file not found, profiling network model on device GPU
[TRT]   device GPU, loading /usr/bin/ MobileNetSSD_deploy.caffemodel
[TRT]   failed to retrieve tensor for Output "softmax"
Segmentation fault (core dumped)
```
### Another Caffe Model
found [here](https://github.com/zhanghanbin3159/MobileNetV2-SSD)

```
./imagenet-console.py airplane_0.jpg output_0.jpg --prototxt=MobileNet-Caffe/mobilenet_v2_deploy.prototxt --model=MobileNet-Caffe/mobilenet_v2.caffemodel --labels=labels_map.txt --input_blob=data --output_blob=softmax
jetson.inference.__init__.py
jetson.inference -- initializing Python 2.7 bindings...
jetson.inference -- registering module types...
jetson.inference -- done registering module types
jetson.inference -- done Python 2.7 binding initialization
jetson.utils.__init__.py
jetson.utils -- initializing Python 2.7 bindings...
jetson.utils -- registering module functions...
jetson.utils -- done registering module functions
jetson.utils -- registering module types...
jetson.utils -- done registering module types
jetson.utils -- done Python 2.7 binding initialization
[image] loaded 'airplane_0.jpg'  (500 x 375, 3 channels)
jetson.inference -- PyTensorNet_New()
jetson.inference -- PyImageNet_Init()
jetson.inference -- imageNet loading network using argv command line params
jetson.inference -- imageNet.__init__() argv[0] = './imagenet-console.py'
jetson.inference -- imageNet.__init__() argv[1] = 'airplane_0.jpg'
jetson.inference -- imageNet.__init__() argv[2] = 'output_0.jpg'
jetson.inference -- imageNet.__init__() argv[3] = '--prototxt=MobileNet-Caffe/mobilenet_v2_deploy.prototxt'
jetson.inference -- imageNet.__init__() argv[4] = '--model=MobileNet-Caffe/mobilenet_v2.caffemodel'
jetson.inference -- imageNet.__init__() argv[5] = '--labels=labels_map.txt'
jetson.inference -- imageNet.__init__() argv[6] = '--input_blob=data'
jetson.inference -- imageNet.__init__() argv[7] = '--output_blob=softmax'

imageNet -- loading classification network model from:
         -- prototxt     MobileNet-Caffe/mobilenet_v2_deploy.prototxt
         -- model        MobileNet-Caffe/mobilenet_v2.caffemodel
         -- class_labels labels_map.txt
         -- input_blob   'data'
         -- output_blob  'softmax'
         -- batch_size   1

[TRT]   TensorRT version 6.0.1
[TRT]   loading NVIDIA plugins...
[TRT]   Plugin Creator registration succeeded - GridAnchor_TRT
[TRT]   Plugin Creator registration succeeded - GridAnchorRect_TRT
[TRT]   Plugin Creator registration succeeded - NMS_TRT
[TRT]   Plugin Creator registration succeeded - Reorg_TRT
[TRT]   Plugin Creator registration succeeded - Region_TRT
[TRT]   Plugin Creator registration succeeded - Clip_TRT
[TRT]   Plugin Creator registration succeeded - LReLU_TRT
[TRT]   Plugin Creator registration succeeded - PriorBox_TRT
[TRT]   Plugin Creator registration succeeded - Normalize_TRT
[TRT]   Plugin Creator registration succeeded - RPROI_TRT
[TRT]   Plugin Creator registration succeeded - BatchedNMS_TRT
[TRT]   Could not register plugin creator:  FlattenConcat_TRT in namespace: 
[TRT]   completed loading NVIDIA plugins.
[TRT]   detected model format - caffe  (extension '.caffemodel')
[TRT]   desired precision specified for GPU: FASTEST
[TRT]   requested fasted precision for device GPU without providing valid calibrator, disabling INT8
[TRT]   native precisions detected for GPU:  FP32, FP16, INT8
[TRT]   selecting fastest native precision for GPU:  FP16
[TRT]   attempting to open engine cache file MobileNet-Caffe/mobilenet_v2.caffemodel.1.1.GPU.FP16.engine
[TRT]   cache file not found, profiling network model on device GPU
[TRT]   device GPU, loading MobileNet-Caffe/mobilenet_v2_deploy.prototxt MobileNet-Caffe/mobilenet_v2.caffemodel
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 98641.7 is outside of [65504, -65504].
Error: Weight 68991.2 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
Error: Weight 99977.8 is outside of [65504, -65504].
[TRT]   device GPU, failed to parse caffe network
[TRT]   device GPU, failed to load MobileNet-Caffe/mobilenet_v2.caffemodel
[TRT]   failed to load MobileNet-Caffe/mobilenet_v2.caffemodel
[TRT]   imageNet -- failed to initialize.
jetson.inference -- imageNet failed to load built-in network 'googlenet'
PyTensorNet_Dealloc()
Traceback (most recent call last):
  File "./imagenet-console.py", line 49, in <module>
    net = jetson.inference.imageNet(opt.network, sys.argv)
Exception: jetson.inference -- imageNet failed to load network
jetson.utils -- freeing CUDA mapped memory

```

<hr>

I know jetson-inference supplies a prebuilt MobileNetV2 + SSD but I am trying to get a custom mobilenetV2 model (personally trained) to work but decided to see if I could get the original to work first (above models).

Ideally I would like to be able to get my custom PyTorch models converted to ONNX (or native PyTorch support?) and run them on the Xavier.

Thank you for any and all help.

**Comment by theDweeb** [comment]
Update: I got my custom model working. The issue with converting PyTorch -> ONNX was some distiller packages for quantization that ONNX did not like. Also, I was setting the --input_blob and output_blob flags to the same name as the ones in the tutorial instead of my ONNX model's input/output name.

**Comment by zoeyhl** [comment]
Hi, could you pls explain what you mean by "ONNX model's input/output name"?
