### ISSUE TITLE
tensorflow-py3 docker image doesn’t work because it contains python2 code 

### ISSUE THREAD

**Issue by Neabfi** [dusty-nv/jetson-inference#502]
I tried to create a dataset on DIGITS using the `nvcr.io/nvidia/digits:20.01-tensorflow-py3` docker image following the instructions from `https://github.com/dusty-nv/jetson-inference/blob/master/docs/segnet-dataset.md`

It seems like the `/opt/digits/digits/tools/create_generic_db.py` still try to run python2 code

> 2020-02-13 21:06:02.096817: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
> Caffe support disabled.
> Reason: A valid Caffe installation was not found on your system.
> 2020-02-13 21:06:03 [ERROR] TypeError: 'range' object does not support item assignment
> Traceback (most recent call last):
> File "/opt/digits/digits/tools/create_generic_db.py", line 480, in <module>
> args['stage']
> File "/opt/digits/digits/tools/create_generic_db.py", line 446, in create_generic_db
> force_same_shape)
> File "/opt/digits/digits/tools/create_generic_db.py", line 298, in create_db
> entry_ids = extension.itemize_entries(stage)
> File "/opt/digits/digits/extensions/data/imageSegmentation/data.py", line 182, in itemize_entries
> feature_image_list = self.split_image_list(feature_image_list, stage)
> File "/opt/digits/digits/extensions/data/imageSegmentation/data.py", line 224, in split_image_list
> random.shuffle(self.random_indices)
> File "/usr/lib/python3.6/random.py", line 277, in shuffle
> x[i], x[j] = x[j], x[i]
> TypeError: 'range' object does not support item assignment

**Comment by Neabfi** [comment]
I found a similar issue [https://github.com/NVIDIA/DIGITS/issues/2208#issue-557221271](https://github.com/NVIDIA/DIGITS/issues/2208#issue-557221271)
