### ISSUE TITLE
Unable to start DIGITS-devserver-Reg

### ISSUE THREAD

**Issue by aswinkumar2019** [dusty-nv/jetson-inference#529]
Hello guys,
We tried to run digits-devserver using the instructions in **https://github.com/dusty-nv/jetson-inference/blob/master/docs/digits-native.md** on i9-9900K CPU with RTX 2080Ti GPU with ubuntu 18.04
We got the error,
|   \_ _/ __|_ _|_   _/ __|
 | |) | | (_ || |  | | \__ \
 |___/___\___|___| |_| |___/ 6.1.1

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/miniscale/digits/digits/__main__.py", line 70, in <module>
    main()
  File "/home/miniscale/digits/digits/__main__.py", line 53, in main
    import digits.config
  File "digits/config/__init__.py", line 7, in <module>
    from . import (  # noqa
  File "digits/config/caffe.py", line 13, in <module>
    from digits.utils import parse_version
  File "digits/utils/__init__.py", line 5, in <module>
    from io import BlockingIOError
  File "/home/miniscale/caffe/python/caffe/io.py", line 2, in <module>
    import skimage.io
**ImportError: No module named skimage.io**

**We tried to install skimage.io using pip install skimage.io and,we got the error,**
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 24, in <module>
    from urllib3.exceptions import DependencyWarning
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/__init__.py", line 8, in <module>
   Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 24, in <module>
    from urllib3.exceptions import DependencyWarning
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/__init__.py", line 8, in <module>
    from .net_spec import layers, params, NetSpec, to_proto
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py", line 11, in <module>
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/exceptions.py", line 2, in <module>
  File "/usr/share/python-wheels/six-1.11.0-py2.py3-none-any.whl/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/share/python-wheels/six-1.11.0-py2.py3-none-any.whl/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/share/python-wheels/six-1.11.0-py2.py3-none-any.whl/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/home/miniscale/caffe/python/caffe/io.py", line 1, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
**ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.**
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: cannot import name multiarray
 from .net_spec import layers, params, NetSpec, to_proto
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/connectionpool.py", line 11, in <module>
  File "/usr/share/python-wheels/urllib3-1.22-py2.py3-none-any.whl/urllib3/exceptions.py", line 2, in <module>
  File "/usr/share/python-wheels/six-1.11.0-py2.py3-none-any.whl/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/share/python-wheels/six-1.11.0-py2.py3-none-any.whl/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/share/python-wheels/six-1.11.0-py2.py3-none-any.whl/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
  File "/usr/lib/python2.7/mimetools.py", line 6, in <module>
    import tempfile
  File "/usr/lib/python2.7/tempfile.py", line 32, in <module>
    import io as _io
  File "/home/miniscale/caffe/python/caffe/io.py", line 1, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

**Original error was: cannot import name multiarray**

**We tried to use pip uninstall numpy and got the same error so,
We did sudo apt remove python-numpy and
sudo apt install python-numpy
and we get the same first error.**

Please help me to fix this and deploy digits.

Regards,
Aswin Kumar

**Comment by aswinkumar2019** [comment]
Hello guys,
              please help me to fix this,waiting for your reply
Regards,
Aswin Kumar
