### ISSUE TITLE
Caffe Support Disabled

### ISSUE THREAD

**Issue by hyattbaker** [dusty-nv/jetson-inference#578]
I have a stand alone UBUNTU machine and NVIDIA Titan GPU. 
I'm trying to go through the Two Days to a Demo and have been through all  the Hello AI stuff, and now I'm to DIGITS.  I have the DIGITS container running and the symbolic link to the 12_classes,  but when I tried to create the dataset I ran into

<pre>2020-05-21 07:54:16.918004: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.2
Caffe support disabled.
Reason: A valid Caffe installation was not found on your system.
Traceback (most recent call last):
File "/opt/digits/digits/tools/parse_folder.py", line 557, in <module>
max_per_category=args['max'],
File "/opt/digits/digits/tools/parse_folder.py", line 442, in parse_folder
test_outfile.write('\n'.join(test_lines) + '\n')
UnboundLocalError: local variable 'test_outfile' referenced before assignment
</pre>

Should have seen that as when DIGITS starts up it also tells me: 
<pre>Caffe support disabled.
Reason: A valid Caffe installation was not found on your system.
</pre>

So that seemed simple enough I went to instructions for caffe native  set up which pointed me to: http://caffe.berkeleyvision.org/installation.html#compilation which led me to running "make all" which led  to 

<pre>(base) <font color="#8AE234"><b>cm@cm-All-Series</b></font>:<font color="#729FCF"><b>~/Downloads/caffe</b></font>$ make all
CXX .build_release/src/caffe/proto/caffe.pb.cc
In file included from .build_release/src/caffe/proto/caffe.pb.cc:4:0:
.build_release/src/caffe/proto/caffe.pb.h:10:10: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include &lt;google/protobuf/port_def.inc&gt;
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:617: recipe for target &apos;.build_release/src/caffe/proto/caffe.pb.o&apos; failed
make: *** [.build_release/src/caffe/proto/caffe.pb.o] Error 1
(base) <font color="#8AE234"><b>cm@cm-All-Series</b></font>:<font color="#729FCF"><b>~/Downloads/caffe</b></font>$ 
</pre>

I'm not sure what to do at this point. I installed protobuf using the SNAP installation but that didn't help.

**Comment by hyattbaker** [comment]
Just to add more clarification to the stand alone Caffe installation attempt, I'm using docker for DIGITS from NGC. On a different approach, I also pulled the docker for NVCaffe from digits and have it running thinking they were to talk to each other, but that didn't work either.

**Comment by hyattbaker** [comment]
So if you find yourself here with the error I listed above, I'm not sure where I went wrong I tried so many things that eventually started with a fresh Ubuntu install and creating a environment for python 3.6 and make sure that when it says "Run commands from the DIGITS server" I docker exec'ed into the container and ran bash commands from the volumes share drives in the container.  All is working now.  Hope it helps. Cheers.
