### ISSUE TITLE
Training Model - Error With Space and Memory

### ISSUE THREAD

**Issue by DJT777** [dusty-nv/jetson-inference#818]
Hi dusty,

I'm working on training my own model and I am getting this error. I am wondering if you would help?

```
dylan@tx1:/media/dylan/SD/jetson-inference/python/training/classification$ sudo python3 train.py --model-dir=models/cat_dog data/cat_dog
Use GPU: 0 for training
=> dataset classes:  2 ['cat', 'dog']
=> using pre-trained model 'resnet18'
Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /home/dylan/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth
100.0%
=> reshaped ResNet fully-connected layer with: Linear(in_features=512, out_features=2, bias=True)
Traceback (most recent call last):
  File "train.py", line 506, in <module>
    main()
  File "train.py", line 135, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 277, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, num_classes, args)
  File "train.py", line 334, in train
    acc1, acc5 = accuracy(output, target, topk=(1, min(5, num_classes)))
  File "train.py", line 500, in accuracy
    correct_k = correct[:k].view(-1).float().sum(0, keepdim=True)
RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

```

df
```
dylan@tx1:/media/dylan/SD/jetson-inference/python/training/classification$ df
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/mmcblk0p1  14384136 13513224    120528 100% /
none             1784664        0   1784664   0% /dev
tmpfs            2029200   229056   1800144  12% /dev/shm
tmpfs            2029200    35736   1993464   2% /run
tmpfs               5120        4      5116   1% /run/lock
tmpfs            2029200        0   2029200   0% /sys/fs/cgroup
/dev/mmcblk2    30308292  7800236  20945432  28% /media/dylan/SD
tmpfs             405840       12    405828   1% /run/user/120
tmpfs             405840      132    405708   1% /run/user/1000

```

**Comment by dusty-nv** [comment]
See https://github.com/dusty-nv/jetson-inference/issues/821#issuecomment-742747607
