### ISSUE TITLE
Unable to train object detection model

### ISSUE THREAD

**Issue by 2g1bz0** [dusty-nv/jetson-inference#831]
hi,
I need help.
I'm following the video.
After downloading the image from the open image dataset, I tried to train train_ssd.py and when I ran the command I got an error like this:
 I think 8GB of memory is enough. 
Why do I get an error?

root@abc-desktop:/jetson-inference/python/training/detection/ssd# python3 train_ssd.py --data=data/fruit --model-dir=models/fruit --batch-size=4 --epochs=1
2020-12-03 08:48:52 - Using CUDA...
2020-12-03 08:48:52 - Namespace(balance_data=False, base_net=None, base_net_lr=0.001, batch_size=4, checkpoint_folder='models/fruit', dataset_type='open_images', datasets=['data/fruit'], debug_steps=10, extra_layers_lr=None, freeze_base_net=False, freeze_net=False, gamma=0.1, lr=0.01, mb2_width_mult=1.0, milestones='80,100', momentum=0.9, net='mb1-ssd', num_epochs=1, num_workers=2, pretrained_ssd='models/mobilenet-v1-ssd-mp-0_675.pth', resume=None, scheduler='cosine', t_max=100, use_cuda=True, validation_epochs=1, weight_decay=0.0005)
2020-12-03 08:48:52 - Prepare training datasets.
2020-12-03 08:48:52 - loading annotations from: data/fruit/sub-train-annotations-bbox.csv
2020-12-03 08:48:52 - annotations loaded from:  data/fruit/sub-train-annotations-bbox.csv
num images:  2022
2020-12-03 08:48:58 - Dataset Summary:Number of Images: 2022
Minimum Number of Images for a Class: -1
Label Distribution:
	Apple: 1466
	Banana: 604
	Grape: 904
	Orange: 2734
	Pear: 356
	Pineapple: 201
	Strawberry: 3402
	Watermelon: 297
2020-12-03 08:48:58 - Stored labels into file models/fruit/labels.txt.
2020-12-03 08:48:58 - Train dataset size: 2022
2020-12-03 08:48:58 - Prepare Validation datasets.
2020-12-03 08:48:58 - loading annotations from: data/fruit/sub-test-annotations-bbox.csv
2020-12-03 08:48:58 - annotations loaded from:  data/fruit/sub-test-annotations-bbox.csv
num images:  365
2020-12-03 08:48:59 - Dataset Summary:Number of Images: 365
Minimum Number of Images for a Class: -1
Label Distribution:
	Apple: 133
	Banana: 50
	Grape: 151
	Orange: 382
	Pear: 36
	Pineapple: 42
	Strawberry: 343
	Watermelon: 51
2020-12-03 08:48:59 - Validation dataset size: 365
2020-12-03 08:48:59 - Build network.
2020-12-03 08:49:00 - Init from pretrained ssd models/mobilenet-v1-ssd-mp-0_675.pth
Traceback (most recent call last):
  File "train_ssd.py", line 309, in <module>
    net.init_from_pretrained_ssd(args.pretrained_ssd)
  File "/jetson-inference/python/training/detection/ssd/vision/ssd/ssd.py", line 119, in init_from_pretrained_ssd
    state_dict = torch.load(model, map_location=lambda storage, loc: storage)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 585, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.6/dist-packages/torch/serialization.py", line 772, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 257966 more bytes. The file might be corrupted.

**Comment by dusty-nv** [comment]
It seems like your `models/mobilenet-v1-ssd-mp-0_675.pth` file may be corrupt.

Can you try running these commands?

``` bash
$ cd jetson-inference/python/training/detection/ssd
$ wget https://nvidia.box.com/shared/static/djf5w54rjvpqocsiztzaandq1m3avr7c.pth -O models/mobilenet-v1-ssd-mp-0_675.pth
```

**Comment by 2g1bz0** [comment]
Thank you
I didn't get any errors during training on train_ssd.py.
but, after exporting, detect failed. In other words, I tried to detect only one image, but the box did not appear.
Why did detect fail?



//This is a state of learning.

root@abc-desktop:/jetson-inference/python/training/detection/ssd# python3 train_ssd.py --data=data/fruit/ --model-dir=models/fruit/ --batch-size=2 --workers=1 --epoch=1
2020-12-08 14:35:00 - Using CUDA...
2020-12-08 14:35:00 - Namespace(balance_data=False, base_net=None, base_net_lr=0.001, batch_size=2, checkpoint_folder='models/fruit/', dataset_type='open_images', datasets=['data/fruit/'], debug_steps=10, extra_layers_lr=None, freeze_base_net=False, freeze_net=False, gamma=0.1, lr=0.01, mb2_width_mult=1.0, milestones='80,100', momentum=0.9, net='mb1-ssd', num_epochs=1, num_workers=1, pretrained_ssd='models/mobilenet-v1-ssd-mp-0_675.pth', resume=None, scheduler='cosine', t_max=100, use_cuda=True, validation_epochs=1, weight_decay=0.0005)
2020-12-08 14:35:00 - Prepare training datasets.
2020-12-08 14:35:00 - loading annotations from: data/fruit/sub-train-annotations-bbox.csv
2020-12-08 14:35:00 - annotations loaded from:  data/fruit/sub-train-annotations-bbox.csv
num images:  2022
2020-12-08 14:35:06 - Dataset Summary:Number of Images: 2022
Minimum Number of Images for a Class: -1
Label Distribution:
	Apple: 1552
	Banana: 610
	Grape: 1130
	Orange: 2452
	Pear: 396
	Pineapple: 219
	Strawberry: 3275
	Watermelon: 265
2020-12-08 14:35:06 - Stored labels into file models/fruit/labels.txt.
2020-12-08 14:35:06 - Train dataset size: 2022
2020-12-08 14:35:06 - Prepare Validation datasets.
2020-12-08 14:35:06 - loading annotations from: data/fruit/sub-test-annotations-bbox.csv
2020-12-08 14:35:06 - annotations loaded from:  data/fruit/sub-test-annotations-bbox.csv
num images:  365
2020-12-08 14:35:08 - Dataset Summary:Number of Images: 365
Minimum Number of Images for a Class: -1
Label Distribution:
	Apple: 135
	Banana: 43
	Grape: 163
	Orange: 260
	Pear: 44
	Pineapple: 39
	Strawberry: 303
	Watermelon: 61
2020-12-08 14:35:08 - Validation dataset size: 365
2020-12-08 14:35:08 - Build network.
2020-12-08 14:35:08 - Init from pretrained ssd models/mobilenet-v1-ssd-mp-0_675.pth
2020-12-08 14:35:10 - Took 1.77 seconds to load the model.
2020-12-08 14:35:39 - Learning rate: 0.01, Base net learning rate: 0.001, Extra Layers learning rate: 0.01.
2020-12-08 14:35:39 - Uses CosineAnnealingLR scheduler.
2020-12-08 14:35:39 - Start training from epoch 0.
/usr/local/lib/python3.6/dist-packages/torch/optim/lr_scheduler.py:123: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/usr/local/lib/python3.6/dist-packages/torch/nn/_reduction.py:44: UserWarning: size_average and reduce args will be deprecated, please use reduction='sum' instead.
  warnings.warn(warning.format(ret))
2020-12-08 14:36:25 - Epoch: 0, Step: 10/1011, Avg Loss: 14.5199, Avg Regression Loss 4.4924, Avg Classification Loss: 10.0275
2020-12-08 14:36:30 - Epoch: 0, Step: 20/1011, Avg Loss: 10.1059, Avg Regression Loss 3.9718, Avg Classification Loss: 6.1341
2020-12-08 14:36:37 - Epoch: 0, Step: 30/1011, Avg Loss: 8.9187, Avg Regression Loss 3.1364, Avg Classification Loss: 5.7823
2020-12-08 14:36:47 - Epoch: 0, Step: 40/1011, Avg Loss: 9.7260, Avg Regression Loss 4.2638, Avg Classification Loss: 5.4623
2020-12-08 14:36:53 - Epoch: 0, Step: 50/1011, Avg Loss: 10.9533, Avg Regression Loss 4.6289, Avg Classification Loss: 6.3244
2020-12-08 14:37:00 - Epoch: 0, Step: 60/1011, Avg Loss: 9.1247, Avg Regression Loss 3.5626, Avg Classification Loss: 5.5621
2020-12-08 14:37:05 - Epoch: 0, Step: 70/1011, Avg Loss: 8.5219, Avg Regression Loss 3.3023, Avg Classification Loss: 5.2197
2020-12-08 14:37:09 - Epoch: 0, Step: 80/1011, Avg Loss: 8.5600, Avg Regression Loss 2.8761, Avg Classification Loss: 5.6838
2020-12-08 14:37:14 - Epoch: 0, Step: 90/1011, Avg Loss: 7.5302, Avg Regression Loss 2.6558, Avg Classification Loss: 4.8744
2020-12-08 14:37:18 - Epoch: 0, Step: 100/1011, Avg Loss: 8.6010, Avg Regression Loss 3.5954, Avg Classification Loss: 5.0056
2020-12-08 14:37:28 - Epoch: 0, Step: 110/1011, Avg Loss: 8.1808, Avg Regression Loss 3.0599, Avg Classification Loss: 5.1209
2020-12-08 14:37:33 - Epoch: 0, Step: 120/1011, Avg Loss: 8.0501, Avg Regression Loss 3.0772, Avg Classification Loss: 4.9729
2020-12-08 14:37:37 - Epoch: 0, Step: 130/1011, Avg Loss: 8.1948, Avg Regression Loss 3.1437, Avg Classification Loss: 5.0511
2020-12-08 14:37:47 - Epoch: 0, Step: 140/1011, Avg Loss: 7.4560, Avg Regression Loss 2.6546, Avg Classification Loss: 4.8014
2020-12-08 14:37:52 - Epoch: 0, Step: 150/1011, Avg Loss: 7.7333, Avg Regression Loss 2.9388, Avg Classification Loss: 4.7945
2020-12-08 14:37:57 - Epoch: 0, Step: 160/1011, Avg Loss: 8.2852, Avg Regression Loss 3.2806, Avg Classification Loss: 5.0046
2020-12-08 14:38:01 - Epoch: 0, Step: 170/1011, Avg Loss: 7.5026, Avg Regression Loss 2.6710, Avg Classification Loss: 4.8316
2020-12-08 14:38:09 - Epoch: 0, Step: 180/1011, Avg Loss: 7.7154, Avg Regression Loss 2.4192, Avg Classification Loss: 5.2962
2020-12-08 14:38:14 - Epoch: 0, Step: 190/1011, Avg Loss: 9.9042, Avg Regression Loss 4.5449, Avg Classification Loss: 5.3593
2020-12-08 14:38:21 - Epoch: 0, Step: 200/1011, Avg Loss: 9.4489, Avg Regression Loss 4.2731, Avg Classification Loss: 5.1758
2020-12-08 14:38:26 - Epoch: 0, Step: 210/1011, Avg Loss: 8.6582, Avg Regression Loss 3.6028, Avg Classification Loss: 5.0554
2020-12-08 14:38:30 - Epoch: 0, Step: 220/1011, Avg Loss: 7.9419, Avg Regression Loss 2.9801, Avg Classification Loss: 4.9618
2020-12-08 14:38:35 - Epoch: 0, Step: 230/1011, Avg Loss: 7.7724, Avg Regression Loss 2.8450, Avg Classification Loss: 4.9274
2020-12-08 14:38:40 - Epoch: 0, Step: 240/1011, Avg Loss: 6.8938, Avg Regression Loss 2.2602, Avg Classification Loss: 4.6337
2020-12-08 14:38:48 - Epoch: 0, Step: 250/1011, Avg Loss: 6.9706, Avg Regression Loss 2.1466, Avg Classification Loss: 4.8240
2020-12-08 14:38:53 - Epoch: 0, Step: 260/1011, Avg Loss: 6.5615, Avg Regression Loss 2.0407, Avg Classification Loss: 4.5207
2020-12-08 14:38:57 - Epoch: 0, Step: 270/1011, Avg Loss: 7.5310, Avg Regression Loss 2.5796, Avg Classification Loss: 4.9514
2020-12-08 14:39:05 - Epoch: 0, Step: 280/1011, Avg Loss: 7.4665, Avg Regression Loss 2.6466, Avg Classification Loss: 4.8199
2020-12-08 14:39:10 - Epoch: 0, Step: 290/1011, Avg Loss: 7.7696, Avg Regression Loss 3.2720, Avg Classification Loss: 4.4976
2020-12-08 14:39:17 - Epoch: 0, Step: 300/1011, Avg Loss: 7.8625, Avg Regression Loss 3.1431, Avg Classification Loss: 4.7194
2020-12-08 14:39:22 - Epoch: 0, Step: 310/1011, Avg Loss: 7.3450, Avg Regression Loss 2.3516, Avg Classification Loss: 4.9934
2020-12-08 14:39:26 - Epoch: 0, Step: 320/1011, Avg Loss: 7.2802, Avg Regression Loss 2.6770, Avg Classification Loss: 4.6032
2020-12-08 14:39:31 - Epoch: 0, Step: 330/1011, Avg Loss: 6.4982, Avg Regression Loss 1.8892, Avg Classification Loss: 4.6090
2020-12-08 14:39:39 - Epoch: 0, Step: 340/1011, Avg Loss: 7.1250, Avg Regression Loss 2.5867, Avg Classification Loss: 4.5383
2020-12-08 14:39:44 - Epoch: 0, Step: 350/1011, Avg Loss: 7.8499, Avg Regression Loss 2.9168, Avg Classification Loss: 4.9332
2020-12-08 14:39:50 - Epoch: 0, Step: 360/1011, Avg Loss: 7.6063, Avg Regression Loss 2.5247, Avg Classification Loss: 5.0817
2020-12-08 14:39:56 - Epoch: 0, Step: 370/1011, Avg Loss: 8.8012, Avg Regression Loss 3.7026, Avg Classification Loss: 5.0986
2020-12-08 14:40:01 - Epoch: 0, Step: 380/1011, Avg Loss: 6.9447, Avg Regression Loss 2.1803, Avg Classification Loss: 4.7644
2020-12-08 14:40:05 - Epoch: 0, Step: 390/1011, Avg Loss: 7.3531, Avg Regression Loss 2.6368, Avg Classification Loss: 4.7163
2020-12-08 14:40:10 - Epoch: 0, Step: 400/1011, Avg Loss: 8.6836, Avg Regression Loss 4.0794, Avg Classification Loss: 4.6042
2020-12-08 14:40:15 - Epoch: 0, Step: 410/1011, Avg Loss: 7.8766, Avg Regression Loss 3.2878, Avg Classification Loss: 4.5888
2020-12-08 14:40:20 - Epoch: 0, Step: 420/1011, Avg Loss: 7.4941, Avg Regression Loss 2.5234, Avg Classification Loss: 4.9707
2020-12-08 14:40:24 - Epoch: 0, Step: 430/1011, Avg Loss: 6.8185, Avg Regression Loss 2.4050, Avg Classification Loss: 4.4135
2020-12-08 14:40:29 - Epoch: 0, Step: 440/1011, Avg Loss: 7.5844, Avg Regression Loss 3.0289, Avg Classification Loss: 4.5554
2020-12-08 14:40:39 - Epoch: 0, Step: 450/1011, Avg Loss: 7.6584, Avg Regression Loss 2.8568, Avg Classification Loss: 4.8016
2020-12-08 14:40:44 - Epoch: 0, Step: 460/1011, Avg Loss: 7.3348, Avg Regression Loss 2.7907, Avg Classification Loss: 4.5441
2020-12-08 14:40:48 - Epoch: 0, Step: 470/1011, Avg Loss: 6.2670, Avg Regression Loss 1.8812, Avg Classification Loss: 4.3857
2020-12-08 14:40:55 - Epoch: 0, Step: 480/1011, Avg Loss: 7.0250, Avg Regression Loss 2.5542, Avg Classification Loss: 4.4708
2020-12-08 14:40:59 - Epoch: 0, Step: 490/1011, Avg Loss: 8.0442, Avg Regression Loss 3.0904, Avg Classification Loss: 4.9538
2020-12-08 14:41:08 - Epoch: 0, Step: 500/1011, Avg Loss: 7.5016, Avg Regression Loss 2.6675, Avg Classification Loss: 4.8340
2020-12-08 14:41:13 - Epoch: 0, Step: 510/1011, Avg Loss: 6.4084, Avg Regression Loss 2.1852, Avg Classification Loss: 4.2232
2020-12-08 14:41:18 - Epoch: 0, Step: 520/1011, Avg Loss: 8.7560, Avg Regression Loss 4.1758, Avg Classification Loss: 4.5802
2020-12-08 14:41:23 - Epoch: 0, Step: 530/1011, Avg Loss: 7.0062, Avg Regression Loss 2.5292, Avg Classification Loss: 4.4770
2020-12-08 14:41:29 - Epoch: 0, Step: 540/1011, Avg Loss: 7.8892, Avg Regression Loss 3.3556, Avg Classification Loss: 4.5336
2020-12-08 14:41:33 - Epoch: 0, Step: 550/1011, Avg Loss: 7.5412, Avg Regression Loss 2.9724, Avg Classification Loss: 4.5688
2020-12-08 14:41:38 - Epoch: 0, Step: 560/1011, Avg Loss: 7.6099, Avg Regression Loss 3.1637, Avg Classification Loss: 4.4461
2020-12-08 14:41:48 - Epoch: 0, Step: 570/1011, Avg Loss: 6.9136, Avg Regression Loss 2.3119, Avg Classification Loss: 4.6017
2020-12-08 14:41:55 - Epoch: 0, Step: 580/1011, Avg Loss: 9.0745, Avg Regression Loss 4.4068, Avg Classification Loss: 4.6677
2020-12-08 14:41:59 - Epoch: 0, Step: 590/1011, Avg Loss: 10.0077, Avg Regression Loss 5.4643, Avg Classification Loss: 4.5434
2020-12-08 14:42:04 - Epoch: 0, Step: 600/1011, Avg Loss: 6.2361, Avg Regression Loss 1.9596, Avg Classification Loss: 4.2765
2020-12-08 14:42:09 - Epoch: 0, Step: 610/1011, Avg Loss: 7.4510, Avg Regression Loss 2.8949, Avg Classification Loss: 4.5561
2020-12-08 14:42:16 - Epoch: 0, Step: 620/1011, Avg Loss: 7.4226, Avg Regression Loss 2.7658, Avg Classification Loss: 4.6568
2020-12-08 14:42:21 - Epoch: 0, Step: 630/1011, Avg Loss: 7.6734, Avg Regression Loss 2.9830, Avg Classification Loss: 4.6904
2020-12-08 14:42:25 - Epoch: 0, Step: 640/1011, Avg Loss: 7.1532, Avg Regression Loss 2.3490, Avg Classification Loss: 4.8042
2020-12-08 14:42:30 - Epoch: 0, Step: 650/1011, Avg Loss: 6.6333, Avg Regression Loss 2.4285, Avg Classification Loss: 4.2048
2020-12-08 14:42:35 - Epoch: 0, Step: 660/1011, Avg Loss: 6.4980, Avg Regression Loss 2.2451, Avg Classification Loss: 4.2529
2020-12-08 14:42:44 - Epoch: 0, Step: 670/1011, Avg Loss: 7.4537, Avg Regression Loss 3.0762, Avg Classification Loss: 4.3775
2020-12-08 14:42:49 - Epoch: 0, Step: 680/1011, Avg Loss: 7.9041, Avg Regression Loss 3.5037, Avg Classification Loss: 4.4004
2020-12-08 14:42:53 - Epoch: 0, Step: 690/1011, Avg Loss: 7.8822, Avg Regression Loss 3.4341, Avg Classification Loss: 4.4482
2020-12-08 14:42:58 - Epoch: 0, Step: 700/1011, Avg Loss: 8.1162, Avg Regression Loss 3.7871, Avg Classification Loss: 4.3291
2020-12-08 14:43:06 - Epoch: 0, Step: 710/1011, Avg Loss: 8.1627, Avg Regression Loss 3.3867, Avg Classification Loss: 4.7759
2020-12-08 14:43:11 - Epoch: 0, Step: 720/1011, Avg Loss: 6.0715, Avg Regression Loss 1.6442, Avg Classification Loss: 4.4273
2020-12-08 14:43:16 - Epoch: 0, Step: 730/1011, Avg Loss: 6.7726, Avg Regression Loss 2.1483, Avg Classification Loss: 4.6243
2020-12-08 14:43:20 - Epoch: 0, Step: 740/1011, Avg Loss: 6.3247, Avg Regression Loss 1.8859, Avg Classification Loss: 4.4388
2020-12-08 14:43:29 - Epoch: 0, Step: 750/1011, Avg Loss: 6.9105, Avg Regression Loss 2.3605, Avg Classification Loss: 4.5500
2020-12-08 14:43:33 - Epoch: 0, Step: 760/1011, Avg Loss: 9.4562, Avg Regression Loss 4.9078, Avg Classification Loss: 4.5484
2020-12-08 14:43:38 - Epoch: 0, Step: 770/1011, Avg Loss: 7.1738, Avg Regression Loss 2.7943, Avg Classification Loss: 4.3795
2020-12-08 14:43:43 - Epoch: 0, Step: 780/1011, Avg Loss: 7.3370, Avg Regression Loss 2.5424, Avg Classification Loss: 4.7945
2020-12-08 14:43:48 - Epoch: 0, Step: 790/1011, Avg Loss: 6.3570, Avg Regression Loss 1.9268, Avg Classification Loss: 4.4302
2020-12-08 14:43:52 - Epoch: 0, Step: 800/1011, Avg Loss: 7.4442, Avg Regression Loss 2.7927, Avg Classification Loss: 4.6515
2020-12-08 14:43:57 - Epoch: 0, Step: 810/1011, Avg Loss: 6.9505, Avg Regression Loss 2.5166, Avg Classification Loss: 4.4339
2020-12-08 14:44:02 - Epoch: 0, Step: 820/1011, Avg Loss: 6.5706, Avg Regression Loss 2.2807, Avg Classification Loss: 4.2899
2020-12-08 14:44:08 - Epoch: 0, Step: 830/1011, Avg Loss: 7.6370, Avg Regression Loss 2.9771, Avg Classification Loss: 4.6599
2020-12-08 14:44:13 - Epoch: 0, Step: 840/1011, Avg Loss: 6.9682, Avg Regression Loss 2.5986, Avg Classification Loss: 4.3696
2020-12-08 14:44:17 - Epoch: 0, Step: 850/1011, Avg Loss: 7.6184, Avg Regression Loss 2.7529, Avg Classification Loss: 4.8656
2020-12-08 14:44:22 - Epoch: 0, Step: 860/1011, Avg Loss: 8.2485, Avg Regression Loss 3.6630, Avg Classification Loss: 4.5855
2020-12-08 14:44:27 - Epoch: 0, Step: 870/1011, Avg Loss: 7.5299, Avg Regression Loss 3.0305, Avg Classification Loss: 4.4994
2020-12-08 14:44:36 - Epoch: 0, Step: 880/1011, Avg Loss: 6.2379, Avg Regression Loss 1.7530, Avg Classification Loss: 4.4849
2020-12-08 14:44:41 - Epoch: 0, Step: 890/1011, Avg Loss: 7.1604, Avg Regression Loss 2.5130, Avg Classification Loss: 4.6473
2020-12-08 14:44:46 - Epoch: 0, Step: 900/1011, Avg Loss: 6.2334, Avg Regression Loss 1.7023, Avg Classification Loss: 4.5312
2020-12-08 14:44:53 - Epoch: 0, Step: 910/1011, Avg Loss: 6.1479, Avg Regression Loss 1.7785, Avg Classification Loss: 4.3693
2020-12-08 14:44:58 - Epoch: 0, Step: 920/1011, Avg Loss: 6.7641, Avg Regression Loss 2.4480, Avg Classification Loss: 4.3160
2020-12-08 14:45:05 - Epoch: 0, Step: 930/1011, Avg Loss: 6.5744, Avg Regression Loss 2.2958, Avg Classification Loss: 4.2786
2020-12-08 14:45:10 - Epoch: 0, Step: 940/1011, Avg Loss: 7.2514, Avg Regression Loss 2.7078, Avg Classification Loss: 4.5436
2020-12-08 14:45:14 - Epoch: 0, Step: 950/1011, Avg Loss: 6.8946, Avg Regression Loss 2.5979, Avg Classification Loss: 4.2967
2020-12-08 14:45:19 - Epoch: 0, Step: 960/1011, Avg Loss: 7.1061, Avg Regression Loss 2.8859, Avg Classification Loss: 4.2202
2020-12-08 14:45:24 - Epoch: 0, Step: 970/1011, Avg Loss: 7.4662, Avg Regression Loss 3.1387, Avg Classification Loss: 4.3275
2020-12-08 14:45:29 - Epoch: 0, Step: 980/1011, Avg Loss: 6.8864, Avg Regression Loss 2.5813, Avg Classification Loss: 4.3052
2020-12-08 14:45:33 - Epoch: 0, Step: 990/1011, Avg Loss: 7.2122, Avg Regression Loss 2.8819, Avg Classification Loss: 4.3302
2020-12-08 14:45:38 - Epoch: 0, Step: 1000/1011, Avg Loss: 6.9349, Avg Regression Loss 2.7818, Avg Classification Loss: 4.1531
2020-12-08 14:45:43 - Epoch: 0, Step: 1010/1011, Avg Loss: 6.9592, Avg Regression Loss 2.4485, Avg Classification Loss: 4.5106
2020-12-08 14:46:16 - Epoch: 0, Validation Loss: 5.8151, Validation Regression Loss 1.5735, Validation Classification Loss: 4.2416
2020-12-08 14:46:16 - Saved model models/fruit/mb1-ssd-Epoch-0-Loss-5.815091200865032.pth
2020-12-08 14:46:16 - Task done, exiting program.
root@abc-desktop:/jetson-inference/python/training/detection/ssd# 









//This is the state of detect.

root@abc-desktop:/jetson-inference/python/training/detection/ssd# detectnet --model=models/fruit/ssd-mobilenet.onnx --labels=models/fruit/labels.txt --input-blob=input_0 --output-cvg=scores --output-bbox=boxes "/jetson-inference/data/images/fruit_0.jpg" /jetson-inference/data/images/test/fruit_0.jpg*
[video]  created imageLoader from file:///jetson-inference/data/images/fruit_0.jpg
------------------------------------------------
imageLoader video options:
------------------------------------------------
  -- URI: file:///jetson-inference/data/images/fruit_0.jpg
     - protocol:  file
     - location:  /jetson-inference/data/images/fruit_0.jpg
     - extension: jpg
  -- deviceType: file
  -- ioType:     input
  -- codec:      unknown
  -- width:      0
  -- height:     0
  -- frameRate:  0.000000
  -- bitRate:    0
  -- numBuffers: 4
  -- zeroCopy:   true
  -- flipMethod: none
  -- loop:       0
------------------------------------------------
[video]  created imageWriter from file:///jetson-inference/data/images/test/fruit_0.jpg
------------------------------------------------
imageWriter video options:
------------------------------------------------
  -- URI: file:///jetson-inference/data/images/test/fruit_0.jpg
     - protocol:  file
     - location:  /jetson-inference/data/images/test/fruit_0.jpg
     - extension: jpg
  -- deviceType: file
  -- ioType:     output
  -- codec:      unknown
  -- width:      0
  -- height:     0
  -- frameRate:  0.000000
  -- bitRate:    0
  -- numBuffers: 4
  -- zeroCopy:   true
  -- flipMethod: none
  -- loop:       0
------------------------------------------------
[OpenGL] glDisplay -- X screen 0 resolution:  1920x1080
[OpenGL] glDisplay -- X window resolution:    1920x1080
[OpenGL] glDisplay -- display device initialized (1920x1080)
[video]  created glDisplay from display://0
------------------------------------------------
glDisplay video options:
------------------------------------------------
  -- URI: display://0
     - protocol:  display
     - location:  0
  -- deviceType: display
  -- ioType:     output
  -- codec:      raw
  -- width:      1920
  -- height:     1080
  -- frameRate:  0.000000
  -- bitRate:    0
  -- numBuffers: 4
  -- zeroCopy:   true
  -- flipMethod: none
  -- loop:       0
------------------------------------------------

detectNet -- loading detection network model from:
          -- prototxt     NULL
          -- model        models/fruit/ssd-mobilenet.onnx
          -- input_blob   'input_0'
          -- output_cvg   'scores'
          -- output_bbox  'boxes'
          -- mean_pixel   0.000000
          -- mean_binary  NULL
          -- class_labels models/fruit/labels.txt
          -- threshold    0.500000
          -- batch_size   1

[TRT]    TensorRT version 7.1.3
[TRT]    loading NVIDIA plugins...
[TRT]    Registered plugin creator - ::GridAnchor_TRT version 1
[TRT]    Registered plugin creator - ::NMS_TRT version 1
[TRT]    Registered plugin creator - ::Reorg_TRT version 1
[TRT]    Registered plugin creator - ::Region_TRT version 1
[TRT]    Registered plugin creator - ::Clip_TRT version 1
[TRT]    Registered plugin creator - ::LReLU_TRT version 1
[TRT]    Registered plugin creator - ::PriorBox_TRT version 1
[TRT]    Registered plugin creator - ::Normalize_TRT version 1
[TRT]    Registered plugin creator - ::RPROI_TRT version 1
[TRT]    Registered plugin creator - ::BatchedNMS_TRT version 1
[TRT]    Could not register plugin creator -  ::FlattenConcat_TRT version 1
[TRT]    Registered plugin creator - ::CropAndResize version 1
[TRT]    Registered plugin creator - ::DetectionLayer_TRT version 1
[TRT]    Registered plugin creator - ::Proposal version 1
[TRT]    Registered plugin creator - ::ProposalLayer_TRT version 1
[TRT]    Registered plugin creator - ::PyramidROIAlign_TRT version 1
[TRT]    Registered plugin creator - ::ResizeNearest_TRT version 1
[TRT]    Registered plugin creator - ::Split version 1
[TRT]    Registered plugin creator - ::SpecialSlice_TRT version 1
[TRT]    Registered plugin creator - ::InstanceNormalization_TRT version 1
[TRT]    detected model format - ONNX  (extension '.onnx')
[TRT]    desired precision specified for GPU: FASTEST
[TRT]    requested fasted precision for device GPU without providing valid calibrator, disabling INT8
[TRT]    native precisions detected for GPU:  FP32, FP16
[TRT]    selecting fastest native precision for GPU:  FP16
[TRT]    attempting to open engine cache file models/fruit/ssd-mobilenet.onnx.1.1.7103.GPU.FP16.engine
[TRT]    loading network plan from engine cache... models/fruit/ssd-mobilenet.onnx.1.1.7103.GPU.FP16.engine
[TRT]    device GPU, loaded models/fruit/ssd-mobilenet.onnx
[TRT]    Deserialize required 11521252 microseconds.
[TRT]    
[TRT]    CUDA engine context initialized on device GPU:
[TRT]       -- layers       104
[TRT]       -- maxBatchSize 1
[TRT]       -- workspace    0
[TRT]       -- deviceMemory 23254528
[TRT]       -- bindings     3
[TRT]       binding 0
                -- index   0
                -- name    'input_0'
                -- type    FP32
                -- in/out  INPUT
                -- # dims  4
                -- dim #0  1 (SPATIAL)
                -- dim #1  3 (SPATIAL)
                -- dim #2  300 (SPATIAL)
                -- dim #3  300 (SPATIAL)
[TRT]       binding 1
                -- index   1
                -- name    'scores'
                -- type    FP32
                -- in/out  OUTPUT
                -- # dims  3
                -- dim #0  1 (SPATIAL)
                -- dim #1  3000 (SPATIAL)
                -- dim #2  9 (SPATIAL)
[TRT]       binding 2
                -- index   2
                -- name    'boxes'
                -- type    FP32
                -- in/out  OUTPUT
                -- # dims  3
                -- dim #0  1 (SPATIAL)
                -- dim #1  3000 (SPATIAL)
                -- dim #2  4 (SPATIAL)
[TRT]    
[TRT]    binding to input 0 input_0  binding index:  0
[TRT]    binding to input 0 input_0  dims (b=1 c=3 h=300 w=300) size=1080000
[TRT]    binding to output 0 scores  binding index:  1
[TRT]    binding to output 0 scores  dims (b=1 c=3000 h=9 w=1) size=108000
[TRT]    binding to output 1 boxes  binding index:  2
[TRT]    binding to output 1 boxes  dims (b=1 c=3000 h=4 w=1) size=48000
[TRT]    
[TRT]    device GPU, models/fruit/ssd-mobilenet.onnx initialized.
[TRT]    detectNet -- number object classes:  9
[TRT]    detectNet -- maximum bounding boxes:  3000
[TRT]    detectNet -- loaded 9 class info entries
[TRT]    detectNet -- number of object classes:  9
[image] loaded '/jetson-inference/data/images/fruit_0.jpg'  (688x1024, 3 channels)
[OpenGL] glDisplay -- set the window size to 688x1024
[OpenGL] creating 688x1024 texture (GL_RGB8 format, 2113536 bytes)
[cuda]   registered openGL texture for interop access (688x1024, GL_RGB8, 2113536 bytes)
[image] saved '/jetson-inference/data/images/test/fruit_0.jpg'  (688x1024, 3 channels)

[TRT]    ------------------------------------------------
[TRT]    Timing Report models/fruit/ssd-mobilenet.onnx
[TRT]    ------------------------------------------------
[TRT]    Pre-Process   CPU   0.08453ms  CUDA   2.06687ms
[TRT]    Network       CPU 136.43465ms  CUDA 133.99661ms
[TRT]    Post-Process  CPU   5.87615ms  CUDA   6.10953ms
[TRT]    Total         CPU 142.39532ms  CUDA 142.17302ms
[TRT]    ------------------------------------------------

[TRT]    note -- when processing a single image, run 'sudo jetson_clocks' before
                to disable DVFS for more accurate profiling/timing measurements

[image] imageLoader -- End of Stream (EOS) has been reached, stream has been closed
detectnet:  shutting down...
detectnet:  shutdown complete.
root@abc-desktop:/jetson-inference/python/training/detection/ssd#

**Comment by dusty-nv** [comment]
It looks like you only trained it for 1 epoch - you would probably need to train it for more epochs (30 is a good start)

BTW here is my fruit model that I trained for 100 epochs:   https://nvidia.box.com/shared/static/gq0zlf0g2r258g3ldabl9o7vch18cxmi.gz

You can try that first and see if it works on your Jetson.

**Comment by 2g1bz0** [comment]
Thank you. It worked very well. The box output nicely.
