### ISSUE TITLE
ERROR: Unexpected segmentation fault encountered in worker. (Object Detection training)

### ISSUE THREAD

**Issue by FugueMaster** [dusty-nv/jetson-inference#956]
Hi Dusty, I was training my model for object detection by using the Person dataset from OpenImages. I downloaded 6000 images (~5500 train images) from there. I had inputted 30 epochs for it to train and this error happens on epoch 15. This error happened the second time after i restart the whole git clone of the jetson-inference repo. Im not sure what to do...and i need help for this cuz its for my final year project.

Command Input:
python3 train_ssd.py --data=data/people --model-dir=models/people --batch-size=4 --workers=2 --epochs=30

2021-03-12 12:44:30 - Epoch: 15, Step: 220/1351, Avg Loss: 3.6073, Avg Regression Loss 1.6280, Avg Classification Loss: 1.9793
2021-03-12 12:44:38 - Epoch: 15, Step: 230/1351, Avg Loss: 3.9874, Avg Regression Loss 1.7574, Avg Classification Loss: 2.2300
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.6/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.6/multiprocessing/connection.py", line 911, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 12680) is killed by signal: Segmentation fault. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_ssd.py", line 343, in <module>
    device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "train_ssd.py", line 113, in train
    for i, data in enumerate(loader):
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 974, in _next_data
    idx, data = self._get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 941, in _get_data
    success, data = self._try_get_data()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 12680) exited unexpectedly

**Comment by dusty-nv** [comment]
Hi there, can you check the memory usage with tegrastats and kernel log with dmesg to see if it is running out of memory?

From: Luna Neo ***@***.***>
Sent: Sunday, March 14, 2021 11:44 PM
To: dusty-nv/jetson-inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dusty-nv/jetson-inference] ERROR: Unexpected segmentation fault encountered in worker. (Object Detection training) (#956)


Hi Dusty, I was training my model for object detection by using the Person dataset from OpenImages. I downloaded 6000 images (~5500 train images) from there. I had inputted 30 epochs for it to train and this error happens on epoch 15. This error happened the second time after i restart the whole git clone of the jetson-inference repo. Im not sure what to do...and i need help for this cuz its for my final year project.

Command Input:
python3 train_ssd.py --data=data/people --model-dir=models/people --batch-size=4 --workers=2 --epochs=30

2021-03-12 12:44:30 - Epoch: 15, Step: 220/1351, Avg Loss: 3.6073, Avg Regression Loss 1.6280, Avg Classification Loss: 1.9793
2021-03-12 12:44:38 - Epoch: 15, Step: 230/1351, Avg Loss: 3.9874, Avg Regression Loss 1.7574, Avg Classification Loss: 2.2300
ERROR: Unexpected segmentation fault encountered in worker.
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 779, in _try_get_data
data = self._data_queue.get(timeout=timeout)
File "/usr/lib/python3.6/multiprocessing/queues.py", line 104, in get
if not self._poll(timeout):
File "/usr/lib/python3.6/multiprocessing/connection.py", line 257, in poll
return self._poll(timeout)
File "/usr/lib/python3.6/multiprocessing/connection.py", line 414, in _poll
r = wait([self], timeout)
File "/usr/lib/python3.6/multiprocessing/connection.py", line 911, in wait
ready = selector.select(timeout)
File "/usr/lib/python3.6/selectors.py", line 376, in select
fd_event_list = self._poll.poll(timeout)
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
_error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 12680) is killed by signal: Segmentation fault.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "train_ssd.py", line 343, in
device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
File "train_ssd.py", line 113, in train
for i, data in enumerate(loader):
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 363, in next
data = self._next_data()
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 974, in _next_data
idx, data = self._get_data()
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 941, in _get_data
success, data = self._try_get_data()
File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 792, in _try_get_data
raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 12680) exited unexpectedly
